select case when cnt>0 then 'Failure' else 'Success' end as Result,
 case when cnt>0 then 'Data Mismatch' else 'Success' end as Message
 from(
select count(1) cnt from (

(select change_request.number,bs.name as n1,coalesce(bs.name,'UNSPECIFIED'), 
case
when coalesce(bs.name,'UNSPECIFIED')= 'Access Management Services' then 'Access Management Services'
when coalesce(bs.name,'UNSPECIFIED')= 'Application Security - Assessment' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Authentication Management' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Autorization Management' then'Autorization Management'
when coalesce(bs.name,'UNSPECIFIED')= 'CDO - SAP Ecosystem & Platform Archtr' then'CDO - SAP Ecosystem & Platform Archtr'
when coalesce(bs.name,'UNSPECIFIED')= 'CDO - SAP Information Security' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'CDS C Customer Data Analytics Solutions' then'CDS C Customer Data Analytics Solutions'
when coalesce(bs.name,'UNSPECIFIED')= 'CDS C Internet of Customers (CRM)' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'CS - Brand Equity Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'CS - CMK & Media Services' then'CS - CMK & Media Services'
when coalesce(bs.name,'UNSPECIFIED')= 'CS AIO' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'CSD - C Account Management' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'CSD - C B2B eCommerce' then'CSD - C B2B eCommerce'
when coalesce(bs.name,'UNSPECIFIED')= 'CSD - C Customer Relationship Mgmt' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'CSD - C Retail Execution' then'CSD - C Retail Execution'
when coalesce(bs.name,'UNSPECIFIED')= 'CSD - C Trade Funds Management' then'CSD - C Trade Funds Management'
when coalesce(bs.name,'UNSPECIFIED')= 'CSD BI Analytics' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - BI CS Media Mgt' then'num_group_no_failure'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - Business Mgmt Intelligence' then'D&A - Business Mgmt Intelligence'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - Data Fabric' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - Data Mgmt Customer Data Svcs' then'D&A - Data Mgmt Customer Data Svcs'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - Data Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - Devops' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - DM Data Capture' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - DM Harmonize & Store' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - Fractal Analytics Services' then'D&A - Fractal Analytics Services'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - MMS' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - Other Reporting Service' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - PS Data Science & Analytics' then'D&A - PS Data Science & Analytics'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - SMO Fastmart/SER' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - SMO Marketscope' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - SMO Retail Execution Alerts' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - SMO RTDC' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - SMO Store Execution Analytics' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A - STC Analytics' then'D&A - STC Analytics'
when coalesce(bs.name,'UNSPECIFIED')= 'D&A – DevOps' then'D&A – DevOps'
when coalesce(bs.name,'UNSPECIFIED')= 'Data Loss Prevention' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'DBCE - Consumer Data Platform' then'DBCE - Consumer Data Platform'
when coalesce(bs.name,'UNSPECIFIED')= 'DBCE - CRM Self Serve Tools' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'DBCE - Digital Presence' then'DBCE - Digital Presence'
when coalesce(bs.name,'UNSPECIFIED')= 'DBCE - Direct to Consumer Selling (DTCS)' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'FPSS-Accounts Receivable Management' then'FPSS-Accounts Receivable Management'
when coalesce(bs.name,'UNSPECIFIED')= 'FPSS-Cash & Banking Management' then'FPSS-Cash & Banking Management'
when coalesce(bs.name,'UNSPECIFIED')= 'FPSS-External Reporting Service' then'FPSS-External Reporting Service'
when coalesce(bs.name,'UNSPECIFIED')= 'FPSS-Financial Accounting Reporting Serv' then'FPSS-Financial Accounting Reporting Serv'
when coalesce(bs.name,'UNSPECIFIED')= 'FPSS-Global Service' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'FPSS-Source Plan Pay Operations' then'FPSS-Source Plan Pay Operations'
when coalesce(bs.name,'UNSPECIFIED')= 'FSS-Forecasting & Reporting' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'FSS-Innovation' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'GBS Financial Management Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Identity and Access Management Service' then'Identity and Access Management Service'
when coalesce(bs.name,'UNSPECIFIED')= 'Identity Management Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'IDQ - Digital Innovation' then'IDQ - Digital Innovation'
when coalesce(bs.name,'UNSPECIFIED')= 'IDQ - Engineering' then'IDQ - Engineering'
when coalesce(bs.name,'UNSPECIFIED')= 'IDQ - Initiative and Design to Print' then'IDQ - Initiative and Design to Print'
when coalesce(bs.name,'UNSPECIFIED')= 'IDQ - Quality' then'IDQ - Quality'
when coalesce(bs.name,'UNSPECIFIED')= 'Information Security Consulting Service' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Insider Risk' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - D&A Hosting Platform' then'ITS - D&A Hosting Platform'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - EAI Engineering' then'ITS - EAI Engineering'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - End Point Devices' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - Enterprise Computing' then'ITS - Enterprise Computing'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - Enterprise ILM' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - IT GRC' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - IT GRC Focus Areas' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - ITSM Ops & Eng' then'ITS - ITSM Ops & Eng'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - Network Infrastructure' then'ITS - Network Infrastructure'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - PS & RD Operations & KLO' then'ITS - PS & RD Operations & KLO'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - RPA Operations & KLO' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS - SAP Operations & KLO' then'ITS - SAP Operations & KLO'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS – Enterprise Computing' then'ITS – Enterprise Computing'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.EIS.Cross Functional Services and Solutions' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.IS.PCI Consultanting Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.ITOpExGov.Service Design' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.Network.Data' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.Network.Operations' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.OpExGov.Application Management Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.Platforms.BI and Analytics Tools' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.Platforms.BI Business Warehouse Platform' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.Platforms.BI Data Provisioning' then'ITS.Platforms.BI Data Provisioning'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.Platforms.Cloud' then'ITS.Platforms.Cloud'
when coalesce(bs.name,'UNSPECIFIED')= 'ITS.Platforms.Mobility and Web Platforms' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MD - Master Data Services' then'MD - Master Data Services'
when coalesce(bs.name,'UNSPECIFIED')= 'MY PG SERVICES-Meeting Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Communication' then'MYPGS - Communication'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Content Creation & Storage' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Content Sharing & Social' then'MYPGS - Content Sharing & Social'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Employee Care' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Employee Care HR' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Employee Data Management' then'MYPGS - Employee Data Management'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Equity Administration' then'MYPGS - Equity Administration'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Expat Payroll & Relo Acct' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Facilities&RealEstateRetained' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Global Payroll Serv' then'MYPGS - Global Payroll Serv'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Global People Mobility' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Global SalaryPlan&Perf Awards' then'MYPGS - Global SalaryPlan&Perf Awards'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - GPMS Delivery Center' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - HR Analytics' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Managed Print Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Meetings' then'MYPGS - Meetings'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Non-US Benefits' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - PC' then'MYPGS - PC'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Site Services' then'MYPGS - Site Services'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - Talent Management' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - US Benefits' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'MYPGS - US Benefits F&A' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Network Security' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-PD-Customs Management Service' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-PD-Shipping Service' then'PISCES-PD-Shipping Service'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-Plng-Category Supply Planning' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-Plng-Demand Planning' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-Plng-Distribution Requirements Planning' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-Plng-Response Management' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-Plng-Site Integrated Planning' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-S2C-Business to Government' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-S2C-CSO Reporting' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-S2C-Customer Care' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-S2C-Order Acquisition' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-S2C-Order Generation (DR, VMI, POS)' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-S2C-Order Generation (EDI, WOM)' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES-S2C-Order Management' then'PISCES-S2C-Order Management'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCeS-STCS-Analytics' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PISCES.DevOps.S2C' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Platform Security' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO - Customer Collaboration' then'PSSS & TO - Customer Collaboration'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO - Cyber Security' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO - Low Dollar Spend' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO - Manufacturing' then'PSSS & TO - Manufacturing'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO - OPS-IT&OT' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO - Order Management IT' then'PSSS & TO - Order Management IT'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO - Order Management Services' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PSSS & TO: Client Manager / RSDM / Org-Work' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'PTW - OPS-IT Operations' then'PTW - OPS-IT Operations'
when coalesce(bs.name,'UNSPECIFIED')= 'PTW - PD-Transportation Service' then'PTW - PD-Transportation Service'
when coalesce(bs.name,'UNSPECIFIED')= 'PTW - PD-Warehouse Management' then'PTW - PD-Warehouse Management'
when coalesce(bs.name,'UNSPECIFIED')= 'PTW - Planning Service' then'PTW - Planning Service'
when coalesce(bs.name,'UNSPECIFIED')= 'S2C-Accounts Receivable' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Security Architecture & Engineering' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Security Ops Center' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Service Delivery & Operations' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Threat Management' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'UNKNOWN' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'UNSPECIFIED' then'num_grouped_others'
when coalesce(bs.name,'UNSPECIFIED')= 'Vulnerability Service' then'num_grouped_others'


end   business_service_grouped,f.business_service_grouped_c


from png_mdsdb.change_request_final change_request
left join png_mdsdb.cmdb_ci_service_final as bs on change_request.business_service = bs.sys_id and change_request.sourceinstance = bs.sourceinstance and 
 change_request.cdctype<>'D' and bs.cdctype<>'D'
join pngcrp_mdwdb.d_change_request d on change_request.sys_id=d.row_id 
and change_request.sourceinstance=d.source_id and change_request.cdctype<>'D' and change_request.state<>'4'
join  pngcrp_mdwdb.d_change_failure f on d.row_key=f.change_request_key and d.source_id=f.source_id 
and f.current_flag='Y'
)
)A



where business_service_grouped<>business_service_grouped_c )a


