


SELECT row_key,row_dn_key,row_current_key,row_id,source_id,etl_run_number,facility_request_number,opened_on,closed_on,due_on,over_due_flag,priority_escalated_flag,first_call_resolution_flag,met_sla_flag,active_flag,domain_key,multiple_assignment_flag,reassignment_count,dormant_flag,short_description,description,knowledge_flag,expected_start,work_start,work_end,room_number,building,backlog_flag,soft_deleted_flag,created_by,changed_by,created_on,changed_on,current_flag,effective_from,effective_to,dw_inserted_on,dw_updated_on
FROM <<tenant>>_mdwdb.d_facility_request
ORDER BY row_key,row_dn_key,row_current_key,row_id,source_id,etl_run_number,facility_request_number,opened_on,closed_on,due_on,over_due_flag,priority_escalated_flag,first_call_resolution_flag,met_sla_flag,active_flag,domain_key,multiple_assignment_flag,reassignment_count,dormant_flag,short_description,description,knowledge_flag,expected_start,work_start,work_end,room_number,building,backlog_flag,soft_deleted_flag,created_by,changed_by,created_on,changed_on,current_flag,effective_from,effective_to,dw_inserted_on,dw_updated_on
