

SELECT CASE WHEN COUNT(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END AS Result, CASE WHEN COUNT(1) > 0 THEN 'Pass through columns from INCIDENT_final to FS_INCIDENT did not match' ELSE 'SUCCESS' END AS Message FROM <<tenant>>_mdsdb.incident_final S 
JOIN app_test.lsm_ls_source_timezone L

ON(S.sourceinstance= L.sourceid)
WHERE CRC32(CONCAT( IFNULL(sys_id,''), IFNULL(sourceinstance,''), IFNULL(number,''), IFNULL(
convert_tz(opened_at,source_time_zone,target_time_zone)
,''), IFNULL(location,''), IFNULL(cmdb_ci,''), IFNULL(assignment_group,''), IFNULL(convert_tz(resolved_at,source_time_zone,target_time_zone),''), IFNULL(convert_tz(closed_at,source_time_zone,target_time_zone),''), IFNULL(convert_tz(due_date,source_time_zone,target_time_zone),''), IFNULL(contact_type,''), IFNULL(category,''), IFNULL(incident_state,''), IFNULL(close_code,''), IFNULL(company,''), IFNULL(problem_id,''), IFNULL(impact,''), IFNULL(urgency,''), IFNULL(severity,''), IFNULL(priority,''), IFNULL(reassignment_count,''), IFNULL(reopen_count,''), IFNULL(time_worked,''), IFNULL(parent_incident,''), IFNULL(sys_domain,''), IFNULL(sys_created_by,''), IFNULL(sys_updated_by,''), IFNULL(sys_created_on,''), IFNULL(sys_updated_on,''), IFNULL(description,''), IFNULL(short_description,''))) NOT IN (SELECT CRC32(CONCAT( IFNULL(row_id,''), IFNULL(source_id,''), IFNULL(incident_number,''), IFNULL(opened_on,''), IFNULL(location_id,''), IFNULL(configuration_item_id,''), IFNULL(assignment_group_id,''), IFNULL(last_resolved_on,''), IFNULL(closed_on,''), IFNULL(due_on,''), IFNULL(reported_type_src_code,''), IFNULL(category_src_code,''), IFNULL(state_src_code,''), IFNULL(close_code_src_code,''), IFNULL(company_id,''), IFNULL(problem_id,''), IFNULL(impact_src_code,''), IFNULL(urgency_src_code,''), IFNULL(severity_src_code,''), IFNULL(priority_src_code,''), IFNULL(reassignment_count,''), IFNULL(reopened_count,''), IFNULL(time_worked,''), IFNULL(parent_incident_id,''), IFNULL(domain_id,''), IFNULL(created_by,''), IFNULL(changed_by,''), IFNULL(created_on,''), IFNULL(changed_on,''), IFNULL(description,''), IFNULL(short_description,''))) FROM <<tenant>>_mdwdb.fs_incident)
