SELECT CASE WHEN CNT>0 THEN concat('FAILURE ON TABLE -',B.table_name) ELSE 'SUCCESS' END FROM 

( 
SELECT COUNT(1) AS CNT,group_concat(A.table_name) as table_name FROM



(SELECT "_num_db_pvttable" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`_num_db_pvttable` UNION 
SELECT "_numerify_dataprofile_statistic_templates" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`_numerify_dataprofile_statistic_templates` UNION 
SELECT "_numerify_dataprofile_statistics" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`_numerify_dataprofile_statistics` UNION 
SELECT "_numerify_dataprofile_statistics_with_dict" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`_numerify_dataprofile_statistics_with_dict` UNION 
SELECT "change_request" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`change_request` UNION 
SELECT "change_request_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`change_request_bwd_delta` UNION 
SELECT "change_request_delta_20150313" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`change_request_delta_20150313` UNION 
SELECT "change_request_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`change_request_final` UNION 
SELECT "cmdb_categories" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_categories` UNION 
SELECT "cmdb_categories_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_categories_bwd_delta` UNION 
SELECT "cmdb_categories_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_categories_final` UNION 
SELECT "cmdb_ci" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci` UNION 
SELECT "cmdb_ci_application" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_application` UNION 
SELECT "cmdb_ci_application_bkp_20150813" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_application_bkp_20150813` UNION 
SELECT "cmdb_ci_application_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_application_bwd_delta` UNION 
SELECT "cmdb_ci_application_bwd_delta_bkp_20150813" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_application_bwd_delta_bkp_20150813` UNION 
SELECT "cmdb_ci_application_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_application_final` UNION 
SELECT "cmdb_ci_application_final_bkp_20150813" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_application_final_bkp_20150813` UNION 
SELECT "cmdb_ci_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_bwd_delta` UNION 
SELECT "cmdb_ci_database" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_database` UNION 
SELECT "cmdb_ci_database_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_database_bwd_delta` UNION 
SELECT "cmdb_ci_database_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_database_final` UNION 
SELECT "cmdb_ci_db_catalog" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_db_catalog` UNION 
SELECT "cmdb_ci_db_catalog_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_db_catalog_bwd_delta` UNION 
SELECT "cmdb_ci_db_catalog_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_db_catalog_final` UNION 
SELECT "cmdb_ci_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_final` UNION 
SELECT "cmdb_ci_outage" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_outage` UNION 
SELECT "cmdb_ci_outage_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_outage_bwd_delta` UNION 
SELECT "cmdb_ci_outage_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_ci_outage_final` UNION 
SELECT "cmdb_model" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_model` UNION 
SELECT "cmdb_model_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_model_bwd_delta` UNION 
SELECT "cmdb_model_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmdb_model_final` UNION 
SELECT "cmn_cost_center" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_cost_center` UNION 
SELECT "cmn_cost_center_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_cost_center_bwd_delta` UNION 
SELECT "cmn_cost_center_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_cost_center_final` UNION 
SELECT "cmn_department" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_department` UNION 
SELECT "cmn_department_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_department_bwd_delta` UNION 
SELECT "cmn_department_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_department_final` UNION 
SELECT "cmn_location" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_location` UNION 
SELECT "cmn_location_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_location_bwd_delta` UNION 
SELECT "cmn_location_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`cmn_location_final` UNION 
SELECT "contract_sla" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`contract_sla` UNION 
SELECT "contract_sla_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`contract_sla_bwd_delta` UNION 
SELECT "contract_sla_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`contract_sla_final` UNION 
SELECT "core_company" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`core_company` UNION 
SELECT "core_company_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`core_company_bwd_delta` UNION 
SELECT "core_company_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`core_company_final` UNION 
SELECT "f_t_task_activity" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`f_t_task_activity` UNION 
SELECT "fiscal_temp" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`fiscal_temp` UNION 
SELECT "fx_currency" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`fx_currency` UNION 
SELECT "fx_currency_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`fx_currency_bwd_delta` UNION 
SELECT "fx_currency_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`fx_currency_final` UNION 
SELECT "fx_rate" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`fx_rate` UNION 
SELECT "fx_rate_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`fx_rate_bwd_delta` UNION 
SELECT "fx_rate_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`fx_rate_final` UNION 
SELECT "incident" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`incident` UNION 
SELECT "incident_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`incident_bwd_delta` UNION 
SELECT "incident_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`incident_final` UNION 
SELECT "internalaudittrail" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`internalaudittrail` UNION 
SELECT "internalentity" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`internalentity` UNION 
SELECT "internalentity_20150813" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`internalentity_20150813` UNION 
SELECT "internallongnames" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`internallongnames` UNION 
SELECT "internalstatus" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`internalstatus` UNION 
SELECT "pc_vendor_cat_item" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`pc_vendor_cat_item` UNION 
SELECT "pc_vendor_cat_item_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`pc_vendor_cat_item_bwd_delta` UNION 
SELECT "pc_vendor_cat_item_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`pc_vendor_cat_item_final` UNION 
SELECT "pm_project" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`pm_project` UNION 
SELECT "pm_project_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`pm_project_bwd_delta` UNION 
SELECT "pm_project_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`pm_project_final` UNION 
SELECT "problem" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`problem` UNION 
SELECT "problem_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`problem_bwd_delta` UNION 
SELECT "problem_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`problem_final` UNION 
SELECT "problem_final_bkp_30092015" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`problem_final_bkp_30092015` UNION 
SELECT "problem_task" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`problem_task` UNION 
SELECT "problem_task_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`problem_task_bwd_delta` UNION 
SELECT "problem_task_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`problem_task_final` UNION 
SELECT "question" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`question` UNION 
SELECT "question_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`question_bwd_delta` UNION 
SELECT "question_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`question_final` UNION 
SELECT "rm_defect" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`rm_defect` UNION 
SELECT "rm_defect_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`rm_defect_bwd_delta` UNION 
SELECT "rm_defect_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`rm_defect_final` UNION 
SELECT "rm_enhancement" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`rm_enhancement` UNION 
SELECT "rm_enhancement_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`rm_enhancement_bwd_delta` UNION 
SELECT "rm_enhancement_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`rm_enhancement_final` UNION 
SELECT "sc_cat_item" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_cat_item` UNION 
SELECT "sc_cat_item_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_cat_item_bwd_delta` UNION 
SELECT "sc_cat_item_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_cat_item_final` UNION 
SELECT "sc_category" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_category` UNION 
SELECT "sc_category_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_category_bwd_delta` UNION 
SELECT "sc_category_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_category_final` UNION 
SELECT "sc_req_item" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_req_item` UNION 
SELECT "sc_req_item_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_req_item_bwd_delta` UNION 
SELECT "sc_req_item_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_req_item_final` UNION 
SELECT "sc_request" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_request` UNION 
SELECT "sc_request_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_request_bwd_delta` UNION 
SELECT "sc_request_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_request_final` UNION 
SELECT "sc_task" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_task` UNION 
SELECT "sc_task_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_task_bwd_delta` UNION 
SELECT "sc_task_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sc_task_final` UNION 
SELECT "sla" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sla` UNION 
SELECT "sla_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sla_bwd_delta` UNION 
SELECT "sla_condition_class" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sla_condition_class` UNION 
SELECT "sla_condition_class_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sla_condition_class_bwd_delta` UNION 
SELECT "sla_condition_class_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sla_condition_class_final` UNION 
SELECT "sla_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sla_final` UNION 
SELECT "survey_conditions" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_conditions` UNION 
SELECT "survey_conditions_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_conditions_bwd_delta` UNION 
SELECT "survey_conditions_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_conditions_final` UNION 
SELECT "survey_instance" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_instance` UNION 
SELECT "survey_instance_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_instance_bwd_delta` UNION 
SELECT "survey_instance_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_instance_final` UNION 
SELECT "survey_master" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_master` UNION 
SELECT "survey_master_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_master_bwd_delta` UNION 
SELECT "survey_master_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_master_final` UNION 
SELECT "survey_question_new" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_question_new` UNION 
SELECT "survey_question_new_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_question_new_bwd_delta` UNION 
SELECT "survey_question_new_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_question_new_final` UNION 
SELECT "survey_response" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_response` UNION 
SELECT "survey_response_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_response_bwd_delta` UNION 
SELECT "survey_response_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`survey_response_final` UNION 
SELECT "sys_audit" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_audit` UNION 
SELECT "sys_audit_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_audit_bwd_delta` UNION 
SELECT "sys_audit_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_audit_final` UNION 
SELECT "sys_choice" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_choice` UNION 
SELECT "sys_choice_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_choice_bwd_delta` UNION 
SELECT "sys_choice_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_choice_final` UNION 
SELECT "sys_db_object" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_db_object` UNION 
SELECT "sys_db_object_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_db_object_bwd_delta` UNION 
SELECT "sys_db_object_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_db_object_final` UNION 
SELECT "sys_dictionary" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_dictionary` UNION 
SELECT "sys_dictionary_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_dictionary_bwd_delta` UNION 
SELECT "sys_dictionary_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_dictionary_final` UNION 
SELECT "sys_user" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user` UNION 
SELECT "sys_user_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_bwd_delta` UNION 
SELECT "sys_user_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_final` UNION 
SELECT "sys_user_grmember" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_grmember` UNION 
SELECT "sys_user_grmember_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_grmember_bwd_delta` UNION 
SELECT "sys_user_grmember_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_grmember_final` UNION 
SELECT "sys_user_group" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_group` UNION 
SELECT "sys_user_group_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_group_bwd_delta` UNION 
SELECT "sys_user_group_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_group_final` UNION 
SELECT "sys_user_group_type" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_group_type` UNION 
SELECT "sys_user_group_type_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_group_type_bwd_delta` UNION 
SELECT "sys_user_group_type_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_group_type_final` UNION 
SELECT "sys_user_has_role" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_has_role` UNION 
SELECT "sys_user_has_role_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_has_role_bwd_delta` UNION 
SELECT "sys_user_has_role_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`sys_user_has_role_final` UNION 
SELECT "task" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task` UNION 
SELECT "task_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_bwd_delta` UNION 
SELECT "task_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_final` UNION 
SELECT "task_sla" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_sla` UNION 
SELECT "task_sla_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_sla_bwd_delta` UNION 
SELECT "task_sla_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_sla_final` UNION 
SELECT "task_survey" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_survey` UNION 
SELECT "task_survey_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_survey_bwd_delta` UNION 
SELECT "task_survey_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`task_survey_final` UNION 
SELECT "temp_doc_key_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`temp_doc_key_final` UNION 
SELECT "time_card" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`time_card` UNION 
SELECT "time_card_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`time_card_bwd_delta` UNION 
SELECT "time_card_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`time_card_final` UNION 
SELECT "u_account" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_account` UNION 
SELECT "u_account_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_account_bwd_delta` UNION 
SELECT "u_account_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_account_final` UNION 
SELECT "u_classification" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_classification` UNION 
SELECT "u_classification_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_classification_bwd_delta` UNION 
SELECT "u_classification_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_classification_final` UNION 
SELECT "u_complexity" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_complexity` UNION 
SELECT "u_complexity_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_complexity_bwd_delta` UNION 
SELECT "u_complexity_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_complexity_final` UNION 
SELECT "u_fiscal_month" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_fiscal_month` UNION 
SELECT "u_fiscal_month_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_fiscal_month_bwd_delta` UNION 
SELECT "u_fiscal_month_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_fiscal_month_final` UNION 
SELECT "u_impact_bs" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_impact_bs` UNION 
SELECT "u_impact_bs_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_impact_bs_bwd_delta` UNION 
SELECT "u_impact_bs_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_impact_bs_final` UNION 
SELECT "u_m2m_accounts_users" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_m2m_accounts_users` UNION 
SELECT "u_m2m_accounts_users_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_m2m_accounts_users_bwd_delta` UNION 
SELECT "u_m2m_accounts_users_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_m2m_accounts_users_final` UNION 
SELECT "u_module" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_module` UNION 
SELECT "u_module_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_module_bwd_delta` UNION 
SELECT "u_module_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_module_final` UNION 
SELECT "u_pm_project_phase" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_pm_project_phase` UNION 
SELECT "u_pm_project_phase_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_pm_project_phase_bwd_delta` UNION 
SELECT "u_pm_project_phase_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_pm_project_phase_final` UNION 
SELECT "u_srt_business_segments" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_srt_business_segments` UNION 
SELECT "u_srt_business_segments_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_srt_business_segments_bwd_delta` UNION 
SELECT "u_srt_business_segments_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_srt_business_segments_final` UNION 
SELECT "u_sys_choice" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_sys_choice` UNION 
SELECT "u_sys_choice_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_sys_choice_bwd_delta` UNION 
SELECT "u_sys_choice_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`u_sys_choice_final` UNION 
SELECT "us_accounttype" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_accounttype` UNION 
SELECT "us_accounttype_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_accounttype_bwd_delta` UNION 
SELECT "us_accounttype_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_accounttype_final` UNION 
SELECT "us_all_hierarchies" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_all_hierarchies` UNION 
SELECT "us_all_hierarchies_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_all_hierarchies_bwd_delta` UNION 
SELECT "us_all_hierarchies_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_all_hierarchies_final` UNION 
SELECT "us_change_request" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request` UNION 
SELECT "us_change_request_age_bucket_lov" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_age_bucket_lov` UNION 
SELECT "us_change_request_age_bucket_lov_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_age_bucket_lov_bwd_delta` UNION 
SELECT "us_change_request_age_bucket_lov_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_age_bucket_lov_final` UNION 
SELECT "us_change_request_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_bwd_delta` UNION 
SELECT "us_change_request_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_final` UNION 
SELECT "us_change_request_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_map` UNION 
SELECT "us_change_request_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_map_bwd_delta` UNION 
SELECT "us_change_request_map_bwd_delta_BKP20150831" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_map_bwd_delta_BKP20150831` UNION 
SELECT "us_change_request_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_map_final` UNION 
SELECT "us_change_request_map_final_BKP20150831" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_change_request_map_final_BKP20150831` UNION 
SELECT "us_city_iso_codes" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_city_iso_codes` UNION 
SELECT "us_city_iso_codes_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_city_iso_codes_bwd_delta` UNION 
SELECT "us_city_iso_codes_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_city_iso_codes_final` UNION 
SELECT "us_city_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_city_map` UNION 
SELECT "us_city_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_city_map_bwd_delta` UNION 
SELECT "us_city_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_city_map_final` UNION 
SELECT "us_country_iso_codes" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_country_iso_codes` UNION 
SELECT "us_country_iso_codes_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_country_iso_codes_bwd_delta` UNION 
SELECT "us_country_iso_codes_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_country_iso_codes_final` UNION 
SELECT "us_country_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_country_map` UNION 
SELECT "us_country_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_country_map_bwd_delta` UNION 
SELECT "us_country_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_country_map_final` UNION 
SELECT "us_currency_iso_codes" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_iso_codes` UNION 
SELECT "us_currency_iso_codes_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_iso_codes_bwd_delta` UNION 
SELECT "us_currency_iso_codes_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_iso_codes_final` UNION 
SELECT "us_currency_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_map` UNION 
SELECT "us_currency_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_map_bwd_delta` UNION 
SELECT "us_currency_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_map_final` UNION 
SELECT "us_currency_rate_type_wh" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_rate_type_wh` UNION 
SELECT "us_currency_rate_type_wh_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_rate_type_wh_bwd_delta` UNION 
SELECT "us_currency_rate_type_wh_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_currency_rate_type_wh_final` UNION 
SELECT "us_employee_termination" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_employee_termination` UNION 
SELECT "us_employee_termination_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_employee_termination_bwd_delta` UNION 
SELECT "us_employee_termination_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_employee_termination_final` UNION 
SELECT "us_fin_status_lov_wh" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_fin_status_lov_wh` UNION 
SELECT "us_fin_status_lov_wh_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_fin_status_lov_wh_bwd_delta` UNION 
SELECT "us_fin_status_lov_wh_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_fin_status_lov_wh_final` UNION 
SELECT "us_financial_kpi" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_financial_kpi` UNION 
SELECT "us_financial_kpi_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_financial_kpi_bwd_delta` UNION 
SELECT "us_financial_kpi_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_financial_kpi_final` UNION 
SELECT "us_gender_iso_codes" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_gender_iso_codes` UNION 
SELECT "us_gender_iso_codes_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_gender_iso_codes_bwd_delta` UNION 
SELECT "us_gender_iso_codes_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_gender_iso_codes_final` UNION 
SELECT "us_gender_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_gender_map` UNION 
SELECT "us_gender_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_gender_map_bwd_delta` UNION 
SELECT "us_gender_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_gender_map_final` UNION 
SELECT "us_hr_change" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_hr_change` UNION 
SELECT "us_hr_change_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_hr_change_bwd_delta` UNION 
SELECT "us_hr_change_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_hr_change_final` UNION 
SELECT "us_hr_change_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_hr_change_map` UNION 
SELECT "us_hr_change_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_hr_change_map_bwd_delta` UNION 
SELECT "us_hr_change_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_hr_change_map_final` UNION 
SELECT "us_incident" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident` UNION 
SELECT "us_incident_age_bucket_lov" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_age_bucket_lov` UNION 
SELECT "us_incident_age_bucket_lov_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_age_bucket_lov_bwd_delta` UNION 
SELECT "us_incident_age_bucket_lov_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_age_bucket_lov_final` UNION 
SELECT "us_incident_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_bwd_delta` UNION 
SELECT "us_incident_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_final` UNION 
SELECT "us_incident_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_map` UNION 
SELECT "us_incident_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_map_bwd_delta` UNION 
SELECT "us_incident_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_incident_map_final` UNION 
SELECT "us_itaa_lov" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itaa_lov` UNION 
SELECT "us_itaa_lov_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itaa_lov_bwd_delta` UNION 
SELECT "us_itaa_lov_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itaa_lov_final` UNION 
SELECT "us_itaa_lov_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itaa_lov_map` UNION 
SELECT "us_itaa_lov_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itaa_lov_map_bwd_delta` UNION 
SELECT "us_itaa_lov_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itaa_lov_map_final` UNION 
SELECT "us_itsm_kpi" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itsm_kpi` UNION 
SELECT "us_itsm_kpi_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itsm_kpi_bwd_delta` UNION 
SELECT "us_itsm_kpi_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itsm_kpi_final` UNION 
SELECT "us_itsm_targets" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itsm_targets` UNION 
SELECT "us_itsm_targets_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itsm_targets_bwd_delta` UNION 
SELECT "us_itsm_targets_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_itsm_targets_final` UNION 
SELECT "us_mds_naturalaccounthier" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_mds_naturalaccounthier` UNION 
SELECT "us_mds_naturalaccounthier_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_mds_naturalaccounthier_bwd_delta` UNION 
SELECT "us_mds_naturalaccounthier_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_mds_naturalaccounthier_final` UNION 
SELECT "us_model_asset_type_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_model_asset_type_map` UNION 
SELECT "us_model_asset_type_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_model_asset_type_map_bwd_delta` UNION 
SELECT "us_model_asset_type_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_model_asset_type_map_final` UNION 
SELECT "us_om_wh_codes" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_om_wh_codes` UNION 
SELECT "us_om_wh_codes_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_om_wh_codes_bwd_delta` UNION 
SELECT "us_om_wh_codes_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_om_wh_codes_final` UNION 
SELECT "us_problem" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem` UNION 
SELECT "us_problem_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_bwd_delta` UNION 
SELECT "us_problem_bwd_delta_BKP20150831" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_bwd_delta_BKP20150831` UNION 
SELECT "us_problem_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_final` UNION 
SELECT "us_problem_final_BKP20150831" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_final_BKP20150831` UNION 
SELECT "us_problem_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_map` UNION 
SELECT "us_problem_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_map_bwd_delta` UNION 
SELECT "us_problem_map_bwd_delta_BKP20150831" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_map_bwd_delta_BKP20150831` UNION 
SELECT "us_problem_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_map_final` UNION 
SELECT "us_problem_map_final_BKP20150831" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_problem_map_final_BKP20150831` UNION 
SELECT "us_question" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_question` UNION 
SELECT "us_question_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_question_bwd_delta` UNION 
SELECT "us_question_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_question_final` UNION 
SELECT "us_question_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_question_map` UNION 
SELECT "us_question_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_question_map_bwd_delta` UNION 
SELECT "us_question_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_question_map_final` UNION 
SELECT "us_request_age_bucket" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_request_age_bucket` UNION 
SELECT "us_request_age_bucket_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_request_age_bucket_bwd_delta` UNION 
SELECT "us_request_age_bucket_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_request_age_bucket_final` UNION 
SELECT "us_s_data_security_group" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group` UNION 
SELECT "us_s_data_security_group_attribute_elements" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_attribute_elements` UNION 
SELECT "us_s_data_security_group_attribute_elements_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_attribute_elements_bwd_delta` UNION 
SELECT "us_s_data_security_group_attribute_elements_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_attribute_elements_final` UNION 
SELECT "us_s_data_security_group_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_bwd_delta` UNION 
SELECT "us_s_data_security_group_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_final` UNION 
SELECT "us_s_data_security_group_user" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_user` UNION 
SELECT "us_s_data_security_group_user_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_user_bwd_delta` UNION 
SELECT "us_s_data_security_group_user_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_s_data_security_group_user_final` UNION 
SELECT "us_sc_req_item" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_req_item` UNION 
SELECT "us_sc_req_item_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_req_item_bwd_delta` UNION 
SELECT "us_sc_req_item_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_req_item_final` UNION 
SELECT "us_sc_req_item_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_req_item_map` UNION 
SELECT "us_sc_req_item_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_req_item_map_bwd_delta` UNION 
SELECT "us_sc_req_item_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_req_item_map_final` UNION 
SELECT "us_sc_request" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_request` UNION 
SELECT "us_sc_request_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_request_bwd_delta` UNION 
SELECT "us_sc_request_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_request_final` UNION 
SELECT "us_sc_request_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_request_map` UNION 
SELECT "us_sc_request_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_request_map_bwd_delta` UNION 
SELECT "us_sc_request_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_sc_request_map_final` UNION 
SELECT "us_state_iso_codes" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_state_iso_codes` UNION 
SELECT "us_state_iso_codes_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_state_iso_codes_bwd_delta` UNION 
SELECT "us_state_iso_codes_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_state_iso_codes_final` UNION 
SELECT "us_state_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_state_map` UNION 
SELECT "us_state_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_state_map_bwd_delta` UNION 
SELECT "us_state_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_state_map_final` UNION 
SELECT "us_task" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task` UNION 
SELECT "us_task_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_bwd_delta` UNION 
SELECT "us_task_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_final` UNION 
SELECT "us_task_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_map` UNION 
SELECT "us_task_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_map_bwd_delta` UNION 
SELECT "us_task_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_map_final` UNION 
SELECT "us_task_sla" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_sla` UNION 
SELECT "us_task_sla_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_sla_bwd_delta` UNION 
SELECT "us_task_sla_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_sla_final` UNION 
SELECT "us_task_sla_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_sla_map` UNION 
SELECT "us_task_sla_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_sla_map_bwd_delta` UNION 
SELECT "us_task_sla_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_task_sla_map_final` UNION 
SELECT "us_time_card" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_time_card` UNION 
SELECT "us_time_card_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_time_card_bwd_delta` UNION 
SELECT "us_time_card_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_time_card_final` UNION 
SELECT "us_time_card_map" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_time_card_map` UNION 
SELECT "us_time_card_map_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_time_card_map_bwd_delta` UNION 
SELECT "us_time_card_map_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_time_card_map_final` UNION 
SELECT "us_tm_keyword_filter" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_tm_keyword_filter` UNION 
SELECT "us_tm_keyword_filter_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_tm_keyword_filter_bwd_delta` UNION 
SELECT "us_tm_keyword_filter_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_tm_keyword_filter_final` UNION 
SELECT "us_units" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_units` UNION 
SELECT "us_units_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_units_bwd_delta` UNION 
SELECT "us_units_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_units_final` UNION 
SELECT "us_wh_finbucket" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_wh_finbucket` UNION 
SELECT "us_wh_finbucket_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_wh_finbucket_bwd_delta` UNION 
SELECT "us_wh_finbucket_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_wh_finbucket_final` UNION 
SELECT "us_wh_itaa_lov" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_wh_itaa_lov` UNION 
SELECT "us_wh_itaa_lov_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_wh_itaa_lov_bwd_delta` UNION 
SELECT "us_wh_itaa_lov_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`us_wh_itaa_lov_final` UNION 
SELECT "wf_stage" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_stage` UNION 
SELECT "wf_stage_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_stage_bwd_delta` UNION 
SELECT "wf_stage_default" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_stage_default` UNION 
SELECT "wf_stage_default_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_stage_default_bwd_delta` UNION 
SELECT "wf_stage_default_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_stage_default_final` UNION 
SELECT "wf_stage_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_stage_final` UNION 
SELECT "wf_workflow_version" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_workflow_version` UNION 
SELECT "wf_workflow_version_bwd_delta" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_workflow_version_bwd_delta` UNION 
SELECT "wf_workflow_version_final" AS table_name, COUNT(*) AS exact_row_count FROM `cardinalhealth_mdsdb`.`wf_workflow_version_final`
) A



where exact_row_count=0)B