select  'ldb.f_incident' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  age,
age_key,
application_key,
assigned_to_key,
assignment_group_c1_key,
assignment_group_c_key,
assignment_group_key,
business_service_key,
caller_by_employee_duration_c_key,
category_5_c_key,
category_src_code,
category_src_key,
caused_by_change_key,
cdctype,
change_request_key,
changed_by,
changed_on,
close_code_src_key,
closed_by_key,
closed_on_key,
company_key,
configuration_item_key,
count_of_opened_by_incidents_c,
created_by,
created_on,
customer_key,
date_key,
domain_key,
dormancy_age,
dormancy_age_key,
due_on_key,
dw_inserted_on,
dw_updated_on,
email_sent_c,
employee_key,
etl_run_number,
fiscal_date_key,
grand_parent_incident_key,
impact_src_key,
inc_employee_count_c,
incident_caused_by_change_fact_pa,
incident_child_count,
incident_key,
incident_priority_de_escalation_count,
incident_priority_escalation_count,
incident_problem_fact_pa,
incident_reopened_count,
last_resolved_by_key,
last_resolved_on_key,
location_key,
method_of_contact_c_key,
opened_by_c1_key,
opened_by_c_key,
opened_by_department_key,
opened_by_employee_duration_c,
opened_by_key,
opened_incidents,
opened_on_key,
opened_time_key,
outage_end_on_key,
outage_end_time_key,
outage_start_on_key,
outage_start_time_key,
p1_downtime_days_c,
parent_incident_key,
priority_src_key,
problem_key,
reassignment_count,
reassignment_count_numerify,
reopened_count,
reported_type_src_key,
resolved_by_group_key,
resolver_department_c_key,
row_id,
row_key,
sd_touch_flag_c_key,
secondary1_changed_on,
secondary2_changed_on,
service_level_src_key,
service_type_c_key,
severity_src_key,
sla_business_duration_c,
soft_deleted_flag,
source_id,
state_src_key,
sub_category_src_code,
sub_category_src_key,
time_key,
type_c_key,
update_count,
updates,
urgency_src_key,
who_is_affected_c_key ,
count(*) as cnt  
from ldb.f_incident group by age,
age_key,
application_key,
assigned_to_key,
assignment_group_c1_key,
assignment_group_c_key,
assignment_group_key,
business_service_key,
caller_by_employee_duration_c_key,
category_5_c_key,
category_src_code,
category_src_key,
caused_by_change_key,
cdctype,
change_request_key,
changed_by,
changed_on,
close_code_src_key,
closed_by_key,
closed_on_key,
company_key,
configuration_item_key,
count_of_opened_by_incidents_c,
created_by,
created_on,
customer_key,
date_key,
domain_key,
dormancy_age,
dormancy_age_key,
due_on_key,
dw_inserted_on,
dw_updated_on,
email_sent_c,
employee_key,
etl_run_number,
fiscal_date_key,
grand_parent_incident_key,
impact_src_key,
inc_employee_count_c,
incident_caused_by_change_fact_pa,
incident_child_count,
incident_key,
incident_priority_de_escalation_count,
incident_priority_escalation_count,
incident_problem_fact_pa,
incident_reopened_count,
last_resolved_by_key,
last_resolved_on_key,
location_key,
method_of_contact_c_key,
opened_by_c1_key,
opened_by_c_key,
opened_by_department_key,
opened_by_employee_duration_c,
opened_by_key,
opened_incidents,
opened_on_key,
opened_time_key,
outage_end_on_key,
outage_end_time_key,
outage_start_on_key,
outage_start_time_key,
p1_downtime_days_c,
parent_incident_key,
priority_src_key,
problem_key,
reassignment_count,
reassignment_count_numerify,
reopened_count,
reported_type_src_key,
resolved_by_group_key,
resolver_department_c_key,
row_id,
row_key,
sd_touch_flag_c_key,
secondary1_changed_on,
secondary2_changed_on,
service_level_src_key,
service_type_c_key,
severity_src_key,
sla_business_duration_c,
soft_deleted_flag,
source_id,
state_src_key,
sub_category_src_code,
sub_category_src_key,
time_key,
type_c_key,
update_count,
updates,
urgency_src_key,
who_is_affected_c_key 
having count(*)>1  ) a
Union
select  'ldb.d_configuration_item' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  application_tier_src_c,
application_tier_src_c_key,
category,
cdctype,
changed_by,
changed_on,
ci_type,
class,
company_key,
created_by,
created_on,
domain_key,
dw_inserted_on,
dw_updated_on,
etl_run_number,
location_key,
managed_by,
manufacturer,
name,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
subcategory,
supported_by,
vendor ,
count(*) as cnt  
from ldb.d_configuration_item group by application_tier_src_c,
application_tier_src_c_key,
category,
cdctype,
changed_by,
changed_on,
ci_type,
class,
company_key,
created_by,
created_on,
domain_key,
dw_inserted_on,
dw_updated_on,
etl_run_number,
location_key,
managed_by,
manufacturer,
name,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
subcategory,
supported_by,
vendor 
having count(*)>1  ) a
Union
select  'ldb.d_internal_contact_assigned_to' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_type_c_key,
etl_run_number,
first_name,
full_name,
geo_key,
image,
last_name,
location_key,
manager,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id
 ,
count(*) as cnt  
from ldb.d_internal_contact_assigned_to group by dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_type_c_key,
etl_run_number,
first_name,
full_name,
geo_key,
image,
last_name,
location_key,
manager,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id
 
having count(*)>1  ) a
Union
select  'ldb.d_internal_organization_group' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
emp_count,
etl_run_number,
lev_0_key,
lev_1_key,
lev_1_organization_name,
lev_2_key,
lev_2_organization_name,
lev_3_key,
lev_3_organization_name,
lev_4_key,
lev_4_organization_name,
lev_5_key,
lev_5_organization_name,
location_key,
manager,
organization_name,
portfolio_src_c,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id
 ,
count(*) as cnt  
from ldb.d_internal_organization_group group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
emp_count,
etl_run_number,
lev_0_key,
lev_1_key,
lev_1_organization_name,
lev_2_key,
lev_2_organization_name,
lev_3_key,
lev_3_organization_name,
lev_4_key,
lev_4_organization_name,
lev_5_key,
lev_5_organization_name,
location_key,
manager,
organization_name,
portfolio_src_c,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id
 
having count(*)>1  ) a
Union
select  'ldb.d_business_service' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
criticality_key,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
name,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
used_for_src_key,
version ,
count(*) as cnt  
from ldb.d_business_service group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
criticality_key,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
name,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
used_for_src_key,
version 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_date' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  calendar_date,
calendar_date_d,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
day_name,
day_name_d,
day_of_month,
day_of_quarter,
day_of_week,
day_of_year,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_days,
lagging_count_of_days_d,
month_id_c,
month_start_date_key,
month_year_c,
previous_day_key,
row_id,
row_key,
same_day_last_week_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
week_day_flag,
week_start_date_c,
week_start_date_key ,
count(*) as cnt  
from ldb.d_calendar_date group by calendar_date,
calendar_date_d,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
day_name,
day_name_d,
day_of_month,
day_of_quarter,
day_of_week,
day_of_year,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_days,
lagging_count_of_days_d,
month_id_c,
month_start_date_key,
month_year_c,
previous_day_key,
row_id,
row_key,
same_day_last_week_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
week_day_flag,
week_start_date_c,
week_start_date_key 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_month' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_month,
lagging_count_of_month_d,
month_end_date,
month_name_abbreviated,
month_start_date,
month_year,
previous_month_key,
quarter_start_date_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_calendar_month group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_month,
lagging_count_of_month_d,
month_end_date,
month_name_abbreviated,
month_start_date,
month_year,
previous_month_key,
quarter_start_date_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_quarter' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_quarter,
lagging_count_of_quarter_c,
lagging_count_of_quarter_d,
previous_quarter_key,
quarter_end_date,
quarter_name,
quarter_number_of_year,
quarter_start_date,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_start_date_key ,
count(*) as cnt  
from ldb.d_calendar_quarter group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_quarter,
lagging_count_of_quarter_c,
lagging_count_of_quarter_d,
previous_quarter_key,
quarter_end_date,
quarter_name,
quarter_number_of_year,
quarter_start_date,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_start_date_key 
having count(*)>1  ) a
Union
select  'ldb.d_incident' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  age,
age_d,
auto_generated_flag,
backlog_flag,
caller_key,
case_id_c,
case_number_c,
category_src_key,
cause_code,
caused_by_change_flag,
cdctype,
change_flag,
changed_by,
changed_on,
close_code_src_key,
closed_before_empstart_c_flag,
closed_by_key,
closed_on,
computer_name_c,
created_by,
created_on,
created_on_c,
description,
domain_key,
dormant_flag,
due_on,
duplicate_incident_flag,
dw_inserted_on,
dw_updated_on,
etl_run_number,
exclude_flag,
first_call_resolution_flag,
first_point_of_contact_resolution_flag,
grand_parent_incident_key,
image_url,
incident_number,
incident_number_c,
incident_number_d,
is_caused_by_change_task_flag,
is_caused_by_task_flag,
knowledge_flag,
last_resolved_on,
major_incident_flag,
met_resolution_sla_flag_key,
met_resolution_sla_on,
met_response_sla_flag_key,
met_response_sla_on,
met_sla_flag,
multiple_assignment_flag,
multiple_categorization_flag,
new_caller_employee_ticket_c_flag,
new_emp_90_tkt_c_flag,
new_employee_ticket_c_flag,
open_lagging_count_of_days,
opened_by_key,
opened_for_self_flag,
opened_on,
opened_on_d,
operating_system_c,
other_c,
over_due_flag,
overall_sla_outcome_flag,
parent_incident_key,
pending_reason,
prefered_phone_c,
priority_de_escalated_flag,
priority_escalated_flag,
priority_src_key,
problem_flag,
reassignee_count,
reassignment_count_numerify,
reminder_stage_c,
reminder_timestamp_c,
reopened_flag,
resolved_by_key,
row_id,
row_key,
row_key_desc,
row_key_short_desc,
sd_touch_c_flag,
secondary1_changed_on,
secondary2_changed_on,
send_notification_c_flag,
severity_src_key,
short_description,
soft_deleted_flag,
source_id,
source_url,
source_url_c,
sr_days_past_due,
sr_days_until_due,
state_src_key,
sub_category_src_key,
temp_rec_number_c,
updated_by_key,
work_item_bi_key_c ,
count(*) as cnt  
from ldb.d_incident group by age,
age_d,
auto_generated_flag,
backlog_flag,
caller_key,
case_id_c,
case_number_c,
category_src_key,
cause_code,
caused_by_change_flag,
cdctype,
change_flag,
changed_by,
changed_on,
close_code_src_key,
closed_before_empstart_c_flag,
closed_by_key,
closed_on,
computer_name_c,
created_by,
created_on,
created_on_c,
description,
domain_key,
dormant_flag,
due_on,
duplicate_incident_flag,
dw_inserted_on,
dw_updated_on,
etl_run_number,
exclude_flag,
first_call_resolution_flag,
first_point_of_contact_resolution_flag,
grand_parent_incident_key,
image_url,
incident_number,
incident_number_c,
incident_number_d,
is_caused_by_change_task_flag,
is_caused_by_task_flag,
knowledge_flag,
last_resolved_on,
major_incident_flag,
met_resolution_sla_flag_key,
met_resolution_sla_on,
met_response_sla_flag_key,
met_response_sla_on,
met_sla_flag,
multiple_assignment_flag,
multiple_categorization_flag,
new_caller_employee_ticket_c_flag,
new_emp_90_tkt_c_flag,
new_employee_ticket_c_flag,
open_lagging_count_of_days,
opened_by_key,
opened_for_self_flag,
opened_on,
opened_on_d,
operating_system_c,
other_c,
over_due_flag,
overall_sla_outcome_flag,
parent_incident_key,
pending_reason,
prefered_phone_c,
priority_de_escalated_flag,
priority_escalated_flag,
priority_src_key,
problem_flag,
reassignee_count,
reassignment_count_numerify,
reminder_stage_c,
reminder_timestamp_c,
reopened_flag,
resolved_by_key,
row_id,
row_key,
row_key_desc,
row_key_short_desc,
sd_touch_c_flag,
secondary1_changed_on,
secondary2_changed_on,
send_notification_c_flag,
severity_src_key,
short_description,
soft_deleted_flag,
source_id,
source_url,
source_url_c,
sr_days_past_due,
sr_days_until_due,
state_src_key,
sub_category_src_key,
temp_rec_number_c,
updated_by_key,
work_item_bi_key_c 
having count(*)>1  ) a
Union
select  'ldb.d_change_request_caused_by' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  assigned_to_key,
assignment_group_key,
category_2_c_key,
category_src,
category_src_key,
cdctype,
change_request_number,
change_request_number_c,
changed_by,
changed_on,
close_code_src_key,
configuration_item_key,
created_by,
created_on,
domain_key,
downtime_c_key,
dw_inserted_on,
dw_updated_on,
etl_run_number,
failure_flag,
grand_parent_change_request_key,
image_url,
implementation_result_code_c_key,
met_sla_flag,
opened_on,
parent_change_request_key,
phase_src_key,
phase_state_src_key,
risk_src,
risk_src_key,
row_id,
row_key,
row_key_short_desc,
scope_src,
scope_src_key,
secondary1_changed_on,
secondary2_changed_on,
short_description,
soft_deleted_flag,
source_id,
source_url,
source_url_c,
tech_validation_c_key,
type_src,
type_src_key,
user_validation_c_key ,
count(*) as cnt  
from ldb.d_change_request_caused_by group by assigned_to_key,
assignment_group_key,
category_2_c_key,
category_src,
category_src_key,
cdctype,
change_request_number,
change_request_number_c,
changed_by,
changed_on,
close_code_src_key,
configuration_item_key,
created_by,
created_on,
domain_key,
downtime_c_key,
dw_inserted_on,
dw_updated_on,
etl_run_number,
failure_flag,
grand_parent_change_request_key,
image_url,
implementation_result_code_c_key,
met_sla_flag,
opened_on,
parent_change_request_key,
phase_src_key,
phase_state_src_key,
risk_src,
risk_src_key,
row_id,
row_key,
row_key_short_desc,
scope_src,
scope_src_key,
secondary1_changed_on,
secondary2_changed_on,
short_description,
soft_deleted_flag,
source_id,
source_url,
source_url_c,
tech_validation_c_key,
type_src,
type_src_key,
user_validation_c_key 
having count(*)>1  ) a
Union
select  'ldb.d_change_request' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  additional_approvers_c,
age,
approval_on,
assigned_to_key,
assignment_group_key,
backlog_flag,
cab_on,
category_2_c,
category_2_c_key,
category_src_key,
cdctype,
change_request_number,
change_request_number_c,
change_request_number_d,
changed_by,
changed_on,
close_code_src_key,
closed_on,
configuration_item_key,
created_by,
created_on,
days_until_planned_start_date,
domain_key,
downtime_c,
downtime_c_key,
due_on,
dw_inserted_on,
dw_updated_on,
emergency_flag,
etl_run_number,
expected_start_on,
failure_flag,
grand_parent_change_request_key,
image,
image_url,
image_url_d,
implementation_plan_c,
implementation_result_code_c,
implementation_result_code_c_key,
met_sla_flag,
not_on_time_flag,
notified_groups_c,
on_hold_flag,
opened_on,
overdue_flag,
parent_change_request_key,
phase_src_key,
phase_state_src_key,
planned_end_on,
planned_start_on,
post_implementation_validation_c,
production_change_flag,
requested_completion_on,
rescheduled_flag,
risk_src_key,
row_id,
row_key,
row_key_short_desc,
scope_src_key,
secondary1_changed_on,
secondary2_changed_on,
short_description,
soft_deleted_flag,
source_id,
source_url,
source_url_c,
source_url_d,
tech_validation_c,
tech_validation_c_key,
type_src_key,
unplanned_flag,
user_validation_c,
user_validation_c_key,
work_end_on,
work_start_on ,
count(*) as cnt  
from ldb.d_change_request group by additional_approvers_c,
age,
approval_on,
assigned_to_key,
assignment_group_key,
backlog_flag,
cab_on,
category_2_c,
category_2_c_key,
category_src_key,
cdctype,
change_request_number,
change_request_number_c,
change_request_number_d,
changed_by,
changed_on,
close_code_src_key,
closed_on,
configuration_item_key,
created_by,
created_on,
days_until_planned_start_date,
domain_key,
downtime_c,
downtime_c_key,
due_on,
dw_inserted_on,
dw_updated_on,
emergency_flag,
etl_run_number,
expected_start_on,
failure_flag,
grand_parent_change_request_key,
image,
image_url,
image_url_d,
implementation_plan_c,
implementation_result_code_c,
implementation_result_code_c_key,
met_sla_flag,
not_on_time_flag,
notified_groups_c,
on_hold_flag,
opened_on,
overdue_flag,
parent_change_request_key,
phase_src_key,
phase_state_src_key,
planned_end_on,
planned_start_on,
post_implementation_validation_c,
production_change_flag,
requested_completion_on,
rescheduled_flag,
risk_src_key,
row_id,
row_key,
row_key_short_desc,
scope_src_key,
secondary1_changed_on,
secondary2_changed_on,
short_description,
soft_deleted_flag,
source_id,
source_url,
source_url_c,
source_url_d,
tech_validation_c,
tech_validation_c_key,
type_src_key,
unplanned_flag,
user_validation_c,
user_validation_c_key,
work_end_on,
work_start_on 
having count(*)>1  ) a
Union
select  'ldb.d_customer' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
customer_mdm_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
organization_name,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_customer group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
customer_mdm_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
organization_name,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_internal_contact' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_mdm_key,
employee_type_c_key,
etl_run_number,
geo_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_contact group by cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_mdm_key,
employee_type_c_key,
etl_run_number,
geo_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_internal_contact_opened_by_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
emp_start_date_d,
emp_start_month_c,
employee_end_date_c,
employee_start_date_c,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
incident_task_emp_end_date_c,
incident_task_emp_start_month_c,
job_family_c,
job_family_d,
job_function_c,
job_function_d,
location_key,
manager_c,
manager_c_key,
region_c,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_contact_opened_by_c group by cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
emp_start_date_d,
emp_start_month_c,
employee_end_date_c,
employee_start_date_c,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
incident_task_emp_end_date_c,
incident_task_emp_start_month_c,
job_family_c,
job_family_d,
job_function_c,
job_function_d,
location_key,
manager_c,
manager_c_key,
region_c,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_internal_contact_caller_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
emp_start_month_c,
employee_end_date_c,
employee_start_date_c,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_contact_caller_c group by cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
emp_start_month_c,
employee_end_date_c,
employee_start_date_c,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_date_fiscal' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  calendar_date,
calendar_date_d,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
day_of_year,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_days,
lagging_count_of_days_d,
period_start_date_key,
previous_year_key,
quarter_start_date_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
week_start_date_key,
year_start_date_key ,
count(*) as cnt  
from ldb.d_calendar_date_fiscal group by calendar_date,
calendar_date_d,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
day_of_year,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_days,
lagging_count_of_days_d,
period_start_date_key,
previous_year_key,
quarter_start_date_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
week_start_date_key,
year_start_date_key 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_time' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  am_pm_indicator,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
hour_24_format_char,
hour_key,
minute_number,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_calendar_time group by am_pm_indicator,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
hour_24_format_char,
hour_key,
minute_number,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_internal_contact_employee_type_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  employee_type_c_key,
row_key ,
count(*) as cnt  
from ldb.d_internal_contact_employee_type_c group by employee_type_c_key,
row_key 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_fiscal_quarter' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_quarter,
lagging_count_of_quarter_c,
lagging_count_of_quarter_d,
previous_year_key,
quarter_name,
quarter_number_of_year,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_start_date_key ,
count(*) as cnt  
from ldb.d_calendar_fiscal_quarter group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_quarter,
lagging_count_of_quarter_c,
lagging_count_of_quarter_d,
previous_year_key,
quarter_name,
quarter_number_of_year,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_start_date_key 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_fiscal_year' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_year,
lagging_count_of_year_c,
lagging_count_of_year_d,
previous_year_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_name,
year_name_d ,
count(*) as cnt  
from ldb.d_calendar_fiscal_year group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_year,
lagging_count_of_year_c,
lagging_count_of_year_d,
previous_year_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_name,
year_name_d 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_week' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_weeks,
lagging_count_of_weeks_c,
lagging_count_of_weeks_d,
previous_week_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
week_end_date,
week_number_of_year,
week_start_date,
week_start_day_name ,
count(*) as cnt  
from ldb.d_calendar_week group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_weeks,
lagging_count_of_weeks_c,
lagging_count_of_weeks_d,
previous_week_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
week_end_date,
week_number_of_year,
week_start_date,
week_start_day_name 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_year' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_year,
lagging_count_of_year_c,
lagging_count_of_year_d,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_name ,
count(*) as cnt  
from ldb.d_calendar_year group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
lagging_count_of_year,
lagging_count_of_year_c,
lagging_count_of_year_d,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
year_name 
having count(*)>1  ) a
Union
select  'ldb.d_internal_organization_group_parent_internal_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
location_key,
parent_row_c_key,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_organization_group_parent_internal_c group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
location_key,
parent_row_c_key,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_employee_duration_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  duration,
duration_c_key,
row_key ,
count(*) as cnt  
from ldb.d_employee_duration_c group by duration,
duration_c_key,
row_key 
having count(*)>1  ) a
Union
select  'ldb.d_internal_organization_legalentity' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
legal_entity_flag,
location_key,
organization_name,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_organization_legalentity group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
legal_entity_flag,
location_key,
organization_name,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_duration_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  duration,
duration_c_key,
row_key ,
count(*) as cnt  
from ldb.d_duration_c group by duration,
duration_c_key,
row_key 
having count(*)>1  ) a
Union
select  'ldb.d_incident_agebucket' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_code,
dimension_name,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_incident_agebucket group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_code,
dimension_name,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_category_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
display_name,
dw_inserted_on,
dw_updated_on,
etl_run_number,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_category_c group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
display_name,
dw_inserted_on,
dw_updated_on,
etl_run_number,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_incident_impact' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id ,
count(*) as cnt  
from ldb.d_incident_impact group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id 
having count(*)>1  ) a
Union
select  'ldb.d_incident_urgency' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id ,
count(*) as cnt  
from ldb.d_incident_urgency group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id 
having count(*)>1  ) a
Union
select  'ldb.d_lov_incident_method_of_contact_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_lov_incident_method_of_contact_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_flag_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  flag_id,
row_key ,
count(*) as cnt  
from ldb.d_flag_c group by flag_id,
row_key 
having count(*)>1  ) a
Union
select  'ldb.d_lov_incident_service_type_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_lov_incident_service_type_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_lov_incident_resolver_department_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_lov_incident_resolver_department_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_location' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
latitude,
location_name,
location_number,
longitude,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
state_code ,
count(*) as cnt  
from ldb.d_location group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
latitude,
location_name,
location_number,
longitude,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
state_code 
having count(*)>1  ) a
Union
select  'ldb.d_lov_incident_type_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_id ,
count(*) as cnt  
from ldb.d_lov_incident_type_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_lov_incident_who_is_affected_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_lov_incident_who_is_affected_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_lov_configuration_item_application_tier_src_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_lov_configuration_item_application_tier_src_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_internal_contact_assigned_to_mdm_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_contact_assigned_to_mdm_c group by cdctype,
changed_by,
changed_on,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_lov_sys_user_group_portfolio_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_lov_sys_user_group_portfolio_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_business_service_criticality' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_name,
wh_row_id ,
count(*) as cnt  
from ldb.d_business_service_criticality group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_name,
wh_row_id 
having count(*)>1  ) a
Union
select  'ldb.d_business_service_used_for' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_name,
wh_row_id ,
count(*) as cnt  
from ldb.d_business_service_used_for group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_name,
wh_row_id 
having count(*)>1  ) a
Union
select  'ldb.d_customer_mdm' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
credit_score,
current_flag,
distributor_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
enduser_flag,
etl_run_number,
organization_name,
reseller_flag,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
state_code ,
count(*) as cnt  
from ldb.d_customer_mdm group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
credit_score,
current_flag,
distributor_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
enduser_flag,
etl_run_number,
organization_name,
reseller_flag,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
state_code 
having count(*)>1  ) a
Union
select  'ldb.d_internal_organization_department' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
location_key,
organization_name,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_organization_department group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
location_key,
organization_name,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_internal_contact_mdm' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
contact_active_flag,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
identification_number,
lev_0_key,
lev_1_full_name,
lev_1_key,
lev_2_full_name,
lev_2_key,
lev_3_full_name,
lev_3_key,
lev_4_full_name,
lev_4_key,
lev_5_full_name,
lev_5_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
vip_flag ,
count(*) as cnt  
from ldb.d_internal_contact_mdm group by cdctype,
changed_by,
changed_on,
contact_active_flag,
cost_center_key,
created_by,
created_on,
current_flag,
department_key,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
employee_type_c_key,
etl_run_number,
full_name,
geo_key,
identification_number,
lev_0_key,
lev_1_full_name,
lev_1_key,
lev_2_full_name,
lev_2_key,
lev_3_full_name,
lev_3_key,
lev_4_full_name,
lev_4_key,
lev_5_full_name,
lev_5_key,
location_key,
manager_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id,
vip_flag 
having count(*)>1  ) a
Union
select  'ldb.d_calendar_time_hour' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
hour_12_format_char,
hour_12_format_num,
hour_24_format_char,
hour_24_format_num,
hour_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_calendar_time_hour group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
dw_inserted_on,
dw_updated_on,
etl_run_number,
hour_12_format_char,
hour_12_format_num,
hour_24_format_char,
hour_24_format_num,
hour_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_incident_close_code' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_id ,
count(*) as cnt  
from ldb.d_incident_close_code group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_lov_sc_req_item_employee_type_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_lov_sc_req_item_employee_type_c group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_incident_priority' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_class,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
lower_range_value,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id ,
count(*) as cnt  
from ldb.d_incident_priority group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_class,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
lower_range_value,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id 
having count(*)>1  ) a
Union
select  'ldb.d_task_sla_resolution_flag' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_code,
dimension_name,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_task_sla_resolution_flag group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_code,
dimension_name,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_task_sla_response_flag' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_code,
dimension_name,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_task_sla_response_flag group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dimension_code,
dimension_name,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_incident_severity' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id ,
count(*) as cnt  
from ldb.d_incident_severity group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id 
having count(*)>1  ) a
Union
select  'ldb.d_incident_state' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id ,
count(*) as cnt  
from ldb.d_incident_state group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id,
wh_dimension_code,
wh_dimension_name,
wh_row_id 
having count(*)>1  ) a
Union
select  'ldb.d_incident_subcategory' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id ,
count(*) as cnt  
from ldb.d_incident_subcategory group by caused_by_change_category_key,
cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
priority_src_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_dimension_code,
source_dimension_name,
source_id 
having count(*)>1  ) a
Union
select  'ldb.d_internal_organization_group_parent_c' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
location_key,
organization_name,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id ,
count(*) as cnt  
from ldb.d_internal_organization_group_parent_c group by cdctype,
changed_by,
changed_on,
created_by,
created_on,
current_flag,
dw_inserted_on,
dw_updated_on,
effective_from,
effective_to,
etl_run_number,
location_key,
organization_name,
portfolio_src_c_key,
row_current_key,
row_dn_key,
row_id,
row_key,
secondary1_changed_on,
secondary2_changed_on,
soft_deleted_flag,
source_id 
having count(*)>1  ) a
union
select  'ldb.f_incident_closed' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  age_key,
application_key,
assigned_to_key,
assignment_group_c1_key,
assignment_group_key,
business_service_key,
caller_by_employee_duration_c_key,
category_5_c_key,
category_src_key,
caused_by_change_key,
cdctype,
change_request_key,
changed_by,
changed_on,
close_code_src_key,
closed_by_key,
closed_incidents,
closed_on_key,
company_key,
configuration_item_key,
created_by,
created_on,
customer_key,
date_key,
domain_key,
dormancy_age_key,
due_on_key,
dw_inserted_on,
dw_updated_on,
employee_key,
etl_run_number,
fiscal_date_key,
grand_parent_incident_key,
impact_src_key,
incident_key,
last_resolved_by_key,
last_resolved_on_key,
location_key,
method_of_contact_c_key,
open_to_close_duration,
opened_by_c1_key,
opened_by_c_key,
opened_by_department_key,
opened_by_employee_duration_c,
opened_by_key,
opened_on_key,
opened_time_key,
outage_end_on_key,
outage_end_time_key,
outage_start_on_key,
outage_start_time_key,
parent_incident_key,
priority_src_key,
problem_key,
reported_type_src_key,
resolved_by_group_key,
resolver_department_c_key,
row_id,
row_key,
sd_touch_flag_c_key,
secondary1_changed_on,
secondary2_changed_on,
service_level_src_key,
service_type_c_key,
severity_src_key,
soft_deleted_flag,
source_id,
state_src_key,
sub_category_src_key,
time_key,
type_c_key,
urgency_src_key,
who_is_affected_c_key ,
count(*) as cnt  
from ldb.f_incident_closed group by age_key,
application_key,
assigned_to_key,
assignment_group_c1_key,
assignment_group_key,
business_service_key,
caller_by_employee_duration_c_key,
category_5_c_key,
category_src_key,
caused_by_change_key,
cdctype,
change_request_key,
changed_by,
changed_on,
close_code_src_key,
closed_by_key,
closed_incidents,
closed_on_key,
company_key,
configuration_item_key,
created_by,
created_on,
customer_key,
date_key,
domain_key,
dormancy_age_key,
due_on_key,
dw_inserted_on,
dw_updated_on,
employee_key,
etl_run_number,
fiscal_date_key,
grand_parent_incident_key,
impact_src_key,
incident_key,
last_resolved_by_key,
last_resolved_on_key,
location_key,
method_of_contact_c_key,
open_to_close_duration,
opened_by_c1_key,
opened_by_c_key,
opened_by_department_key,
opened_by_employee_duration_c,
opened_by_key,
opened_on_key,
opened_time_key,
outage_end_on_key,
outage_end_time_key,
outage_start_on_key,
outage_start_time_key,
parent_incident_key,
priority_src_key,
problem_key,
reported_type_src_key,
resolved_by_group_key,
resolver_department_c_key,
row_id,
row_key,
sd_touch_flag_c_key,
secondary1_changed_on,
secondary2_changed_on,
service_level_src_key,
service_type_c_key,
severity_src_key,
soft_deleted_flag,
source_id,
state_src_key,
sub_category_src_key,
time_key,
type_c_key,
urgency_src_key,
who_is_affected_c_key 
having count(*)>1  ) a
Union
select  'ldb.f_incident_resolved' as tablename,  case when a.cnt = 0 then 'SUCCESS' else 'FAILURE'end as Result
from (
select  adv_incident_sla_business_duration_c,
age,
age_key,
application_key,
assigned_to_key,
assignment_group_c1_key,
assignment_group_key,
business_duration_c,
business_service_key,
caller_by_employee_duration_c_key,
category_5_c_key,
category_src_key,
caused_by_change_key,
cdctype,
change_request_key,
changed_by,
changed_on,
close_code_src_key,
closed_by_key,
closed_on_key,
company_key,
configuration_item_key,
created_by,
created_on,
customer_key,
date_key,
domain_key,
dormancy_age_key,
due_on_key,
dw_inserted_on,
dw_updated_on,
employee_key,
etl_run_number,
fiscal_date_key,
grand_parent_incident_key,
impact_src_key,
incident_age_fact_resolved,
incident_key,
incident_ntt_duration_c,
incident_open_to_resolve_duration,
incident_reassignment_count_numerify_resolved_fact,
incident_sla_business_duration_c,
last_resolved_by_key,
last_resolved_on_key,
location_key,
method_of_contact_c_key,
opened_by_c1_key,
opened_by_c_key,
opened_by_department_key,
opened_by_employee_duration_c,
opened_by_key,
opened_on_key,
opened_time_key,
outage_end_on_key,
outage_end_time_key,
outage_start_on_key,
outage_start_time_key,
parent_incident_key,
priority_src_key,
problem_key,
reassignment_count_numerify,
reported_type_src_key,
resolve_to_close_duration,
resolved_by_group_key,
resolved_incidents,
resolver_department_c_key,
row_id,
row_key,
sd_touch_flag_c_key,
secondary1_changed_on,
secondary2_changed_on,
service_level_src_key,
service_type_c_key,
severity_src_key,
sla_business_duration_c,
soft_deleted_flag,
source_id,
state_src_key,
sub_category_src_key,
time_key,
type_c_key,
update_count,
updates_resolved,
urgency_src_key,
who_is_affected_c_key ,
count(*) as cnt  
from ldb.f_incident_resolved group by adv_incident_sla_business_duration_c,
age,
age_key,
application_key,
assigned_to_key,
assignment_group_c1_key,
assignment_group_key,
business_duration_c,
business_service_key,
caller_by_employee_duration_c_key,
category_5_c_key,
category_src_key,
caused_by_change_key,
cdctype,
change_request_key,
changed_by,
changed_on,
close_code_src_key,
closed_by_key,
closed_on_key,
company_key,
configuration_item_key,
created_by,
created_on,
customer_key,
date_key,
domain_key,
dormancy_age_key,
due_on_key,
dw_inserted_on,
dw_updated_on,
employee_key,
etl_run_number,
fiscal_date_key,
grand_parent_incident_key,
impact_src_key,
incident_age_fact_resolved,
incident_key,
incident_ntt_duration_c,
incident_open_to_resolve_duration,
incident_reassignment_count_numerify_resolved_fact,
incident_sla_business_duration_c,
last_resolved_by_key,
last_resolved_on_key,
location_key,
method_of_contact_c_key,
opened_by_c1_key,
opened_by_c_key,
opened_by_department_key,
opened_by_employee_duration_c,
opened_by_key,
opened_on_key,
opened_time_key,
outage_end_on_key,
outage_end_time_key,
outage_start_on_key,
outage_start_time_key,
parent_incident_key,
priority_src_key,
problem_key,
reassignment_count_numerify,
reported_type_src_key,
resolve_to_close_duration,
resolved_by_group_key,
resolved_incidents,
resolver_department_c_key,
row_id,
row_key,
sd_touch_flag_c_key,
secondary1_changed_on,
secondary2_changed_on,
service_level_src_key,
service_type_c_key,
severity_src_key,
sla_business_duration_c,
soft_deleted_flag,
source_id,
state_src_key,
sub_category_src_key,
time_key,
type_c_key,
update_count,
updates_resolved,
urgency_src_key,
who_is_affected_c_key 
having count(*)>1  ) a


