

SELECT CASE WHEN COUNT(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END AS Result,CASE WHEN COUNT(1) > 0 
THEN 'Lookup for #COL_NAME did not match #REF_TABLE_NAME' ELSE 'SUCCESS' END AS Message
FROM (SELECT 1 FROM #REF_TABLE_NAME DCD JOIN <<tenant>>_mdsdb.#MDS_TABLE_NAME BASE
ON DCD.#REF_COL_NAME = BASE.#MDS_COL_NAME
WHERE CONCAT(BASE.#REF_COL_NAME ,#REF_RETURN_NAME)   NOT IN (SELECT CONCAT( row_id, #STG_COL_NAME)
FROM <<tenant>>_workdb.#STG_TABLE_NAME)) A
