select ci.category as "configuration item category" , ci.ci_team as "configuration item ci team", ci.ci_type as "configuration item ci team" , ci.class as "configuration item class",
''as metric,sum(case when di.auto_generated_flag = 'Y' then 1 else 0 end) as "autogenerated flag"
,sum(case when di.duplicate_incident_flag = 'Y' then 1 else 0 end) as "Incidents closed as duplicate"
,sum(case when di.duplicate_incident_flag = 'Y' then 1 else 0 end) as "Duplicate Incidents"
,sum(case when di.closed_without_intervention_flag  ='Y' then 1 else 0 end) as "incident closed with no manual intervention"
,sum(case when di.closed_without_intervention_flag  ='Y' or di.duplicate_incident_flag = 'Y'then 1 else 0 end) as "incident closed without action"
from  #DWH_TABLE_SCHEMA.f_incident fi 
join #DWH_TABLE_SCHEMA.d_internal_contact dc
on  fi.opened_by_key = dc.row_key
join #DWH_TABLE_SCHEMA.d_incident di
on  fi.incident_key = di.row_key
join #DWH_TABLE_SCHEMA.d_calendar_date dcd
on  fi.opened_on_key = dcd.row_key
 join #DWH_TABLE_SCHEMA.d_internal_organization dio 
on fi.opened_by_department_key = dio.row_key
join  #DWH_TABLE_SCHEMA.d_lov  dv 
on fi.state_src_key  = dv.row_key
join  #DWH_TABLE_SCHEMA.d_lov_map dvm
on dvm.dimension_code  = dv.dimension_code
and dvm.dimension_class=dv.dimension_class
join #DWH_TABLE_SCHEMA.d_domain dom
on dom.row_key = fi.domain_key
join #DWH_TABLE_SCHEMA.d_configuration_item ci 
on fi.configuration_item_key = ci.row_key
where dcd.lagging_count_of_month between 0 and 12
group by ci.category , ci_team,ci_type ,ci.class
order by ci.category,ci_team,ci_type ,ci.class
