SELECT CASE WHEN CntSrc <>CntTrgt THEN 'FAILURE' ELSE 'SUCCESS' END AS Result,
CASE WHEN CntSrc <>CntTrgt THEN CONCAT('#TABLE_NAME doesnt have', CAST(CntSrc AS CHAR(10)),' expected -1 for #COLUMN_NAME') 
ELSE 'SUCCESS' END AS Message
FROM (SELECT COUNT(1) CntSrc
FROM #SRC_TABLE TRGTS
LEFT JOIN #SRC_LKPTABLE LKPS
ON(TRGTS.problem_id=LKPS.sys_id
AND TRGTS.sourceinstance=LKPS.sourceinstance)
WHERE LKPS.sys_id IS NULL AND TRGTS.#SRC_COLNAME IS NOT NULL) SRC
,(SELECT COUNT(1) CntTrgt 
FROM #TABLE_NAME TRGTD
WHERE #COLUMN_NAME=-1) TRGT
