SELECT COALESCE(replace(`dimension_code`,',',''),''),
    COALESCE(`is_customization`,''),
    COALESCE(`is_mandatory`,''),
    COALESCE(`map_table_name_column`,''),
    COALESCE(`enable_flag`,''),
    COALESCE(replace(`filter`,'#TENANT_NAME',''),''),
    COALESCE(`map_table_name`,''),
    COALESCE(`source_id`,''),
    COALESCE(`source_table`,''),
    COALESCE(`source_name`,''),
    COALESCE(`dimension_class`,''),
    COALESCE(`dimension_name`,''),
    COALESCE(replace(`source_row_id`,',',''),'')
from #STAGE_TABLE_SCHEMA.lsm_ls_lov_metadata order by `dimension_code`,
    `is_customization`,
    `is_mandatory`,
    `map_table_name_column`,
    `enable_flag`,
    `filter`,
    `map_table_name`,
    `source_id`,
    `source_table`,
    `source_name`,
    `dimension_class`,
    `dimension_name`,
    `source_row_id`;