SELECT CASE WHEN CntUnknown > 0 THEN 'FAILURE' ELSE 'SUCCESS' END AS Result,
CASE WHEN CntUnknown > 0 THEN CONCAT('#TABLE_NAME has', CAST(CntUnknown AS CHAR(10)),' #COLUMN_NAME as -1 out of '
, CAST(CntTotal AS CHAR(10)),' records' ) 
ELSE '#TABLE_NAME has no #COLUMN_NAME -1' END AS Message
FROM (SELECT COUNT(1) CntUnknown 
FROM #TABLE_NAME TRGT
JOIN #LKPTABLE LKP
ON(TRGT.#COLUMN_NAME=LKP.row_key
AND TRGT.source_id=LKP.source_id)
WHERE TRGT.#COLUMN_NAME = -1 AND TRGT.row_id NOT IN ('UNKNOWN','UNSPECIFIED')
AND LKP.row_id NOT IN (#IGNORE_ID)) A
,(SELECT COUNT(1) CntTotal 
FROM #TABLE_NAME TRGT
JOIN #LKPTABLE LKP
ON(TRGT.#COLUMN_NAME=LKP.row_key
AND TRGT.source_id=LKP.source_id)
WHERE LKP.row_id NOT IN (#IGNORE_ID)) B