 select `dwh_view`,
    `type`,
    `target_table`,
    `day_of_week_month`,
    `dwh_current_view`,
    `enable_flag`,
    `retention`,
    `custom_flag`,
    `calendar_code`,
    `current_flag`,
    `subject_area`,
    `sequence_id`,
    `source_id`,
    `table_type`,
    `dwh_table`
from #STAGE_TABLE_SCHEMA.lsm_ls_dw_aggregator WHERE subject_area <>'FIN'
order by `dwh_view`,
    `type`,
    `target_table`,
    `day_of_week_month`,
    `dwh_current_view`,
    `enable_flag`,
    `retention`,
    `custom_flag`,
    `calendar_code`,
    `current_flag`,
    `subject_area`,
    `sequence_id`,
    `source_id`,
    `table_type`,
    `dwh_table`;