SELECT CASE WHEN count(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END as Result,
CASE WHEN count(1) >0 THEN 'MDS to DWH row count failed for d_lov.lower_range_value' ELSE 'SUCCESS' END as Message
from (select * from  #MDS_TABLE_SCHEMA.hp_knta_lookups_nls_final  where cdctype<>'D') SRC
left join  #DWH_TABLE_SCHEMA.d_lov TRGT
on CONCAT(CASE 
WHEN UPPER(SRC.LOOKUP_TYPE)='PMO - ISSUE IMPACT LEVEL' THEN 'PROJECT_RISK~ESCALATION' 
WHEN UPPER(SRC.LOOKUP_TYPE)='ISSUE_PRIORITY' THEN 'PROJECT_RISK~PRIORITY' 
WHEN UPPER(SRC.LOOKUP_TYPE)='PMO - RISK IMPACT' THEN 'PROJECT_RISK~IMPACT' 
WHEN UPPER(SRC.LOOKUP_TYPE)='PMO - RISK PROBABILITY' THEN 'PROJECT_RISK~PROBABILITY' 
WHEN UPPER(SRC.LOOKUP_TYPE)='PMO - RISK TYPES' THEN 'PROJECT_RISK~TYPE' END,'~',SRC.LOOKUP_CODE)
=TRGT.row_id
and SRC.sourceinstance=TRGT.source_id

where 
UPPER(SRC.DEFINITION_LANGUAGE)='AMERICAN' and UPPER(SRC.LOOKUP_TYPE) 
in ('PMO - ISSUE IMPACT LEVEL','ISSUE_PRIORITY','PMO - RISK IMPACT','PMO - RISK PROBABILITY','PMO - RISK TYPES')
and 
coalesce(TRGT.lower_range_value,'')
<>null;