select TABLE_NAME,view_definition from information_schema.views
where TABLE_NAME in('dh_assignment_group_tier_hierarchy',
'dh_assignment_group_tier_hierarchy_level1',
'dh_assignment_group_tier_hierarchy_level2',
'dh_assignment_group_tier_hierarchy_level3',
'dh_assignment_group_tier_hierarchy_level4',
'dh_assignment_group_tier_hierarchy_level5',
'dh_assignment_group_type_hierarchy',
'dh_assignment_group_type_hierarchy_level1',
'dh_assignment_group_type_hierarchy_level2',
'dh_assignment_group_type_hierarchy_level3',
'dh_assignment_group_type_hierarchy_level4',
'dh_assignment_group_type_hierarchy_level5',
'dh_employee_region_hierarchy',
'dh_employee_region_level1',
'dh_employee_region_level2',
'dh_employee_region_level3',
'dh_employee_region_level4',
'dh_employee_region_level5',
'dh_location_region_hierarchy',
'dh_location_region_level1',
'dh_location_region_level2',
'dh_location_region_level3',
'dh_location_region_level4',
'dh_location_region_level5',
'dh_user_group_classification_hierarchy',
'dh_user_group_classification_hierarchy_level1',
'dh_user_group_classification_hierarchy_level2',
'dh_user_group_classification_hierarchy_level3',
'dh_user_group_classification_hierarchy_level4',
'dh_user_group_classification_hierarchy_level5',
'dh_user_group_region_tier_hierarchy',
'dh_user_group_region_tier_level1',
'dh_user_group_region_tier_level2',
'dh_user_group_region_tier_level3',
'dh_user_group_region_tier_level4',
'dh_user_group_region_tier_level5')
order by TABLE_NAME