select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_application' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_application UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_calendar_date' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_calendar_date UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_calendar_list' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_calendar_list UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_calendar_time' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_calendar_time UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_change_request' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_change_request UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_configuration_item' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_configuration_item UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_contact' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_contact UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_cost_center' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_cost_center UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_domain' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_domain UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_fiscal_period' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_fiscal_period UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_fiscal_quarter' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_fiscal_quarter UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_fiscal_year' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_fiscal_year UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_geography' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_geography UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_h_all_hierarchies' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_h_all_hierarchies UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_hr_change' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_hr_change UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_hr_employee' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_hr_employee UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_incident' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_incident UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_internal_contact' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_internal_contact UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_internal_organization' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_internal_organization UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_keyword_filter' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_keyword_filter UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_location' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_location UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_lov' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_lov UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_lov_map' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_lov_map UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_master_item' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_master_item UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_month' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_month UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_problem' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_problem UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_problem_task' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_problem_task UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_request_item' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_request_item UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_request_task' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_request_task UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_survey' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_survey UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_survey_instance' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_survey_instance UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_survey_question' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_survey_question UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_task' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_task UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_task_sla' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_task_sla UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_o_data_freshness' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_o_data_freshness UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_outage' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_outage UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_problem_task' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_problem_task UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_request' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_request UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_request_task' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_request_task UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_service' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_service UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_survey' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_survey UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_survey_instance' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_survey_instance UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_survey_question' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_survey_question UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_task' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_task UNION ALL 
select case when count(distinct etl_run_number)<3 then 'FULL LOAD' else 'INCREMENTAL LOAD' END LOAD_TYPE,'d_year' DIM_TABLE from  #DWH_TABLE_SCHEMA.d_year 
