
SELECT call_key	,
call_number	,
call_type_src_code	,
call_type_src_key	,
caller_key	,
cdctype	,
changed_by	,
changed_on	,
company_key	,
created_by	,
created_on	,
department_key	,
domain_key	,
dw_inserted_on	,
dw_updated_on	,
etl_run_number	,
location_key	,
master_item_key	,
opened_by_key	,
opened_on_key	,
opened_time_key	,
pivot_date	,
reported_type_src_code	,
reported_type_src_key	,
row_id	,
row_key	,
secondary1_changed_on	,
secondary2_changed_on	,
soft_deleted_flag	,
source_id	,
task_key	,
time_spent	
 FROM #DWH_TABLE_SCHEMA.f_call 
ORDER BY call_key	,
call_number	,
call_type_src_code	,
call_type_src_key	,
caller_key	,
cdctype	,
changed_by	,
changed_on	,
company_key	,
created_by	,
created_on	,
department_key	,
domain_key	,
dw_inserted_on	,
dw_updated_on	,
etl_run_number	,
location_key	,
master_item_key	,
opened_by_key	,
opened_on_key	,
opened_time_key	,
pivot_date	,
reported_type_src_code	,
reported_type_src_key	,
row_id	,
row_key	,
secondary1_changed_on	,
secondary2_changed_on	,
soft_deleted_flag	,
source_id	,
task_key	,
time_spent	

