select out1.source_id,
out1.etl_run_number, 
 out1.row_key, out1.row_id, 
 out1.outage_number, 
 out1.soft_deleted_flag, 
 out1.outage_key, 
 out1.start_on_key, 
 out1.start_time_key, 
 out1.end_on_key, 
 out1.configuration_item_key, 
 out1.business_service_key, 
 out1.application_key, 
 out1.caused_by_change_key, 
 COALESCE(fcr.change_request_key, 0) AS change_request_key, 
 out1.outage_duration, 
 out1.updates_count,  
out1.created_by, 
out1.created_on, 
out1.changed_by, 
out1.changed_on, 
out1.dw_inserted_on, 
out1.dw_updated_on,
fcr.assigned_to_key,
fcr.assignment_group_key,
fcr.category_src_key,
fcr.impact_src_key,
fcr.priority_src_key,
fcr.reason_src_key,
fcr.reported_type_src_key,
fcr.review_status_src_key,
fcr.state_src_key,
fcr.risk_src_key,
fcr.scope_src_key,
fcr.type_src_key,
fcr.urgency_src_key,
fcr.configuration_item_key as change_request_configuration_item_key,
fcr.domain_key,
fcr.requested_by_department_key,
fcr.opened_by_key,
fcr.requested_by_key,
fcr.location_key,
fcr.opened_on_key

from #DWH_TABLE_SCHEMA.f_change_request fcr
join #DWH_TABLE_SCHEMA.d_change_request dcr 
on dcr.row_key=fcr.change_request_key
and fcr.soft_deleted_flag <> 'Y'
join #DWH_TABLE_SCHEMA.f_outage out1 
on fcr.row_key = out1.change_request_key
and out1.soft_deleted_flag <> 'Y'
order by
out1.source_id,
out1.etl_run_number, 
 out1.row_key, out1.row_id, 
 out1.outage_number, 
 out1.soft_deleted_flag, 
 out1.outage_key, 
 out1.start_on_key, 
 out1.start_time_key, 
 out1.end_on_key, 
 out1.configuration_item_key, 
 out1.business_service_key, 
 out1.application_key, 
 out1.caused_by_change_key, 
 COALESCE(fcr.change_request_key, 0) , 
 out1.outage_duration, 
 out1.updates_count,  
out1.created_by, 
out1.created_on, 
out1.changed_by, 
out1.changed_on, 
out1.dw_inserted_on, 
out1.dw_updated_on,
fcr.assigned_to_key,
fcr.assignment_group_key,
fcr.category_src_key,
fcr.impact_src_key,
fcr.priority_src_key,
fcr.reason_src_key,
fcr.reported_type_src_key,
fcr.review_status_src_key,
fcr.state_src_key,
fcr.risk_src_key,
fcr.scope_src_key,
fcr.type_src_key,
fcr.urgency_src_key,
fcr.configuration_item_key ,
fcr.domain_key,
fcr.requested_by_department_key,
fcr.opened_by_key,
fcr.requested_by_key,
fcr.location_key,
fcr.opened_on_key
