 SELECT f_task_sla.row_key, f_task_sla.row_id, f_task_sla.source_id, f_task_sla.etl_run_number, f_task_sla.task_type, f_task_sla.sla_key, f_task_sla.incident_key, f_task_sla.problem_key, f_task_sla.request_key, f_task_sla.request_item_key, f_task_sla.request_task_key, f_task_sla.problem_task_key, f_task_sla.start_on_key, f_task_sla.start_time_key, f_task_sla.due_on_key, f_task_sla.end_on_key, f_task_sla.stage_src_key, f_task_sla.stage_src_code, f_task_sla.outcome_flag, f_task_sla.actual_duration, f_task_sla.percentage_taken, f_task_sla.pause_duration, f_task_sla.soft_deleted_flag, f_task_sla.created_by, f_task_sla.changed_by, f_task_sla.created_on, f_task_sla.changed_on, f_task_sla.dw_inserted_on, f_task_sla.dw_updated_on, f_task_sla.exclude_flag, f_incident.assignment_group_key, f_incident.priority_src_key, f_incident.state_src_key, f_incident.age_key
   ,f_incident.opened_on_key ,f_incident.last_resolved_on_key
   FROM #DWH_TABLE_SCHEMA.f_task_sla f_task_sla
   JOIN #DWH_TABLE_SCHEMA.f_incident f_incident ON f_task_sla.incident_key = f_incident.incident_key AND f_incident.soft_deleted_flag = 'N' AND f_task_sla.soft_deleted_flag = 'N'
WHERE f_task_sla.task_type = 'INCIDENT'
 order by 
  f_task_sla.row_key, f_task_sla.row_id, f_task_sla.source_id, f_task_sla.etl_run_number, f_task_sla.task_type, f_task_sla.sla_key, f_task_sla.incident_key, f_task_sla.problem_key, f_task_sla.request_key, f_task_sla.request_item_key, f_task_sla.request_task_key, f_task_sla.problem_task_key, f_task_sla.start_on_key, f_task_sla.start_time_key, f_task_sla.due_on_key, f_task_sla.end_on_key, f_task_sla.stage_src_key, f_task_sla.stage_src_code, f_task_sla.outcome_flag, f_task_sla.actual_duration, f_task_sla.percentage_taken, f_task_sla.pause_duration, f_task_sla.soft_deleted_flag, f_task_sla.created_by, f_task_sla.changed_by, f_task_sla.created_on, f_task_sla.changed_on, f_task_sla.dw_inserted_on, f_task_sla.dw_updated_on, f_task_sla.exclude_flag, f_incident.assignment_group_key, f_incident.priority_src_key, f_incident.state_src_key, f_incident.age_key
   ,f_incident.opened_on_key ,f_incident.last_resolved_on_key;

