


SELECT CASE WHEN count(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END as Result,
 CASE WHEN count(1) >0 THEN 'MDS to DWH data validation failed for f_time_card' 
 ELSE 'SUCCESS' END as Message FROM 
 (


SELECT MIN(QUERY) AS DIFFERENCE
 ,	ROW_ID
,	SOURCE_ID
,TIMECARD_SOURCE_ID
,	TIMECARD_NUMBER
,	TIMECARD_ON_KEY
,	TIMECARD_TIME_KEY
,	EMPLOYEE_KEY
,	DEPARTMENT_KEY
,	LOCATION_KEY
,	COST_CENTER_KEY
,	DOMAIN_KEY
,	TASK_KEY
,	CATEGORY_SRC_KEY
,	STATE_SRC_KEY
,	PROJECT_KEY
,	COMPANY_KEY
,	CATEGORY_SRC_CODE
,	STATE_SRC_CODE
,	TIME_ENTERED
,DESCRIPTION
-- ,SOURCE_URL
-- ,	SOFT_DELETED_FLAG
,	CREATED_BY
,	CHANGED_BY
,	CREATED_ON
,	CHANGED_ON
-- ,timecard_id

FROM(
select 'SRC_TEST' as query
,	ROW_ID
,	SOURCE_ID
,TIMECARD_SOURCE_ID
,	TIMECARD_NUMBER
,	TIMECARD_ON_KEY
,	 TIMECARD_TIME_KEY
,	EMPLOYEE_KEY
,	DEPARTMENT_KEY
,	LOCATION_KEY
,	COST_CENTER_KEY
,	DOMAIN_KEY
,	TASK_KEY
,	CATEGORY_SRC_KEY
,	STATE_SRC_KEY
, PROJECT_KEY
,	COMPANY_KEY
,	CATEGORY_SRC_CODE
,	STATE_SRC_CODE
,	TIME_ENTERED

,DESCRIPTION
-- ,SOURCE_URL
-- ,	SOFT_DELETED_FLAG
,	CREATED_BY
,	CHANGED_BY
,	CREATED_ON
,	CHANGED_ON
-- ,null as timecard_id

from app_test.temp_time_card_mddw_test
union all
select 'TRGT_TEST' as query
,	ROW_ID
,	SOURCE_ID
,TIMECARD_SRC_ID
,	TIMECARD_NUMBER
,	TIMECARD_ON_KEY
,	TIMECARD_TIME_KEY
,	EMPLOYEE_KEY
,	DEPARTMENT_KEY
,	LOCATION_KEY
,	COST_CENTER_KEY
,	DOMAIN_KEY
,	TASK_KEY
,	CATEGORY_SRC_KEY
,	STATE_SRC_KEY
,	PROJECT_KEY
,	COMPANY_KEY
,	CATEGORY_SRC_CODE
,	STATE_SRC_CODE
,	TIME_ENTERED
,DESCRIPTION
-- ,SOURCE_URL
-- ,	SOFT_DELETED_FLAG

,	CREATED_BY
,	CHANGED_BY
,	CREATED_ON
,	CHANGED_ON
-- ,timecard_id

from #DWH_TABLE_SCHEMA.f_time_card
WHERE SOFT_DELETED_FLAG<>'Y'
) CMP
GROUP BY
ROW_ID
,	SOURCE_ID
,TIMECARD_SOURCE_ID
,	TIMECARD_NUMBER
,	TIMECARD_ON_KEY
,	TIMECARD_TIME_KEY
,	EMPLOYEE_KEY
,	DEPARTMENT_KEY
,	LOCATION_KEY
,	COST_CENTER_KEY
,	DOMAIN_KEY
,	TASK_KEY
,	CATEGORY_SRC_KEY
,	STATE_SRC_KEY
,	PROJECT_KEY
,	COMPANY_KEY
,	CATEGORY_SRC_CODE
,	STATE_SRC_CODE
,	TIME_ENTERED
,DESCRIPTION
-- ,SOURCE_URL
-- ,	SOFT_DELETED_FLAG
,	CREATED_BY
,	CHANGED_BY
,	CREATED_ON
,	CHANGED_ON
-- ,timecard_id

HAVING COUNT(*)<>2
ORDER BY ROW_ID


) RESULT


