select case when count(1)>0 then 'FAILURE' else 'SUCCESS' end as result
,case when count(1)>0 then 'soft_deleted_flag<>"Y" does not exists for few views' else 'SUCCESS' end as message
from pg_views
where viewname in ('d_ap_credit_memo_application',
 'd_ap_credit_memo_detail',
 'd_ap_invoice_detail',
 'd_ar_cash_sale_detail',
 'd_ar_credit_memo_application',
 'd_ar_credit_memo_detail',
 'd_ar_ct_deposit_application',
 'd_ar_ct_refund',
 'd_ar_invoice_detail',
 'd_ar_payment_application',
 'f_asset',
 'f_asset_status_history',
 'f_fin_customer_relationship_profile',
 'f_fin_vendor_relationship_profile',
 'f_financials_target_day',
 'f_financials_target_fiscal_period',
 'f_financials_target_fiscal_quarter',
 'f_financials_target_fiscal_year',
 'f_financials_target_month',
 'f_financials_target_quarter',
 'f_financials_target_year',
 'f_n_expense_item_monthly',
 'f_n_expense_item_quarterly',
 'f_n_expense_item_weekly',
 'f_asset_status_monthly_duration',
 'f_asset_status_weekly_duration',
 'f_gl_balance',
 'f_gl_budget',
 'f_gl_journal',
 'f_n_asset_monthly',
 'f_n_asset_quarterly',
 'f_n_asset_status_history_monthly',
 'f_n_asset_status_history_quarterly',
 'f_n_asset_status_history_weekly',
 'f_n_asset_weekly',
 'f_n_asset_yearly',
 'n_ap_credit_memo_summary_monthly',
 'n_ap_invoice_monthly',
 'n_ap_payment_monthly',
 'n_ar_credit_memo_summary_monthly',
 'n_ar_ct_deposit_monthly',
 'n_ar_ct_refund_monthly',
 'n_ar_invoice_monthly',
 'n_ar_payment_monthly',
 'so_po_cube_final',
 'ITSM views where the soft_deleted_flag condition is missing :',
 'f_change_request_keyword',
 'f_employee_termination',
 'f_hr_change',
 'f_incident_keyword',
 'f_itsm_target_day',
 'f_itsm_target_month',
 'f_itsm_target_quarter',
 'f_itsm_target_year',
 'f_oldest_incident_agent',
 'f_problem_keyword',
 'f_request_item_keyword',
 'f_time_card',
 'f_n_incident_monthly',
 'f_n_incident_weekly',
 'f_change_request_closed',
 'f_facility_request_closed',
 'f_request_closed')
and  (definition  not   like '%WHERE%soft^_deleted^_flag^<^>' escape '^'
or definition  not   like '%AND%soft^_deleted^_flag^<^>' escape '^')