SELECT CASE WHEN count(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END as Result,
CASE WHEN count(1) >0 THEN 'MDS to DWH data validation failed for d_calendar_date.day_of_quarter' ELSE 'SUCCESS' END as Message
FROM  wow_mdsdb.DS_DATE_SEED SRC
LEFT OUTER JOIN (SELECT MIN(`DATE`) AS date1 FROM wow_mdsdb.DS_DATE_SEED 
  WHERE DATE BETWEEN '1970-01-01 00:00:00' AND '2030-12-31 00:00:00'
  GROUP BY CONCAT(DATE_FORMAT(`DATE`,'%Y'),QUARTER(`DATE`))) AS SRC3
ON SRC.CAST(CONCAT(DATE_FORMAT(SRC.`DATE`,'%Y'),QUARTER(SRC.`DATE`)) AS SIGNED) = CONCAT(DATE_FORMAT(SRC3.DATE1,'%Y'),QUARTER(SRC3.DATE1))
WHERE SRC.`DATE` BETWEEN '1970-01-01 00:00:00' AND '2030-12-31 00:00:00'
AND TIMESTAMPDIFF(DAY,SRC3.date1,q1.CALENDAR_DATE) +1<>TRGT.day_of_quarter
