SELECT CASE WHEN COUNT(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END AS Result
, CASE WHEN COUNT(1) > 0 THEN '#VIEW_NAME does not match data from d_lov' ELSE 'SUCCESS' END AS Message
FROM ldb.#VIEW_NAME
WHERE COALESCE(CAST(row_key AS TEXT ),'')|| COALESCE(CAST(row_dn_key AS TEXT ),'')|| COALESCE(CAST(row_current_key AS TEXT ),'')|| COALESCE(CAST(row_id AS TEXT ),'')|| COALESCE(CAST(source_id AS TEXT ),'')|| COALESCE(CAST(etl_run_number AS TEXT ),'')|| COALESCE(CAST(src_rowid AS TEXT ),'')|| COALESCE(CAST(dimension_class AS TEXT ),'')|| COALESCE(CAST(dimension_type AS TEXT ),'')|| COALESCE(CAST(dimension_subtype AS TEXT ),'')|| COALESCE(CAST(dimension_code AS TEXT ),'')|| COALESCE(CAST(dimension_name AS TEXT ),'')|| COALESCE(CAST(lower_range_value AS TEXT ),'')|| COALESCE(CAST(upper_range_value AS TEXT ),'')|| COALESCE(CAST(soft_deleted_flag AS TEXT ),'')|| COALESCE(CAST(created_by AS TEXT ),'')|| COALESCE(CAST(changed_by AS TEXT ),'')|| COALESCE(CAST(created_on AS TEXT ),'')|| COALESCE(CAST(changed_on AS TEXT ),'')|| COALESCE(CAST(current_flag AS TEXT ),'')|| COALESCE(CAST(effective_from AS TEXT ),'')|| COALESCE(CAST(effective_to AS TEXT ),'')|| COALESCE(CAST(dw_inserted_on AS TEXT ),'')|| COALESCE(CAST(dw_updated_on AS TEXT ),'')
NOT IN (SELECT COALESCE(CAST(row_key AS TEXT ),'')|| COALESCE(CAST(row_dn_key AS TEXT ),'')|| COALESCE(CAST(row_current_key AS TEXT ),'')|| COALESCE(CAST(row_id AS TEXT ),'')|| COALESCE(CAST(source_id AS TEXT ),'')|| COALESCE(CAST(etl_run_number AS TEXT ),'')|| COALESCE(CAST(src_rowid AS TEXT ),'')|| COALESCE(CAST(dimension_class AS TEXT ),'')|| COALESCE(CAST(dimension_type AS TEXT ),'')|| COALESCE(CAST(dimension_subtype AS TEXT ),'')|| COALESCE(CAST(dimension_code AS TEXT ),'')|| COALESCE(CAST(dimension_name AS TEXT ),'')|| COALESCE(CAST(lower_range_value AS TEXT ),'')|| COALESCE(CAST(upper_range_value AS TEXT ),'')|| COALESCE(CAST(soft_deleted_flag AS TEXT ),'')|| COALESCE(CAST(created_by AS TEXT ),'')|| COALESCE(CAST(changed_by AS TEXT ),'')|| COALESCE(CAST(created_on AS TEXT ),'')|| COALESCE(CAST(changed_on AS TEXT ),'')|| COALESCE(CAST(current_flag AS TEXT ),'')|| COALESCE(CAST(effective_from AS TEXT ),'')|| COALESCE(CAST(effective_to AS TEXT ),'')|| COALESCE(CAST(dw_inserted_on AS TEXT ),'')|| COALESCE(CAST(dw_updated_on AS TEXT ),'')
FROM <<tenant>>_mdwdb.d_lov
WHERE dimension_class  = '#DIMENSION_CLASS'
UNION 
SELECT COALESCE(CAST(row_key AS TEXT ),'')|| COALESCE(CAST(row_dn_key AS TEXT ),'')|| COALESCE(CAST(row_current_key AS TEXT ),'')|| COALESCE(CAST(row_id AS TEXT ),'')|| COALESCE(CAST(source_id AS TEXT ),'')|| COALESCE(CAST(etl_run_number AS TEXT ),'')|| COALESCE(CAST(src_rowid AS TEXT ),'')|| COALESCE(CAST(dimension_class AS TEXT ),'')|| COALESCE(CAST(dimension_type AS TEXT ),'')|| COALESCE(CAST(dimension_subtype AS TEXT ),'')|| COALESCE(CAST(dimension_code AS TEXT ),'')|| COALESCE(CAST(dimension_name AS TEXT ),'')|| COALESCE(CAST(lower_range_value AS TEXT ),'')|| COALESCE(CAST(upper_range_value AS TEXT ),'')|| COALESCE(CAST(soft_deleted_flag AS TEXT ),'')|| COALESCE(CAST(created_by AS TEXT ),'')|| COALESCE(CAST(changed_by AS TEXT ),'')|| COALESCE(CAST(created_on AS TEXT ),'')|| COALESCE(CAST(changed_on AS TEXT ),'')|| COALESCE(CAST(current_flag AS TEXT ),'')|| COALESCE(CAST(effective_from AS TEXT ),'')|| COALESCE(CAST(effective_to AS TEXT ),'')|| COALESCE(CAST(dw_inserted_on AS TEXT ),'')|| COALESCE(CAST(dw_updated_on AS TEXT ),'')
FROM <<tenant>>_mdwdb.d_lov d_lov
WHERE row_key = -1 OR row_key = 0)
