
SELECT row_id	,
row_key	,
secondary1_changed_on	,
short_description	,
source_url	,
secondary2_changed_on	,
domain_key	,
dw_inserted_on	,
etl_run_number	,
opened_on	,
call_number	,
soft_deleted_flag	,
changed_on	,
changed_by	,
description	,
source_id	,
created_by	,
dw_updated_on	,
created_on	,
cdctype	
 FROM <<tenant>>_mdwdb.d_call 
ORDER BY row_id	,
row_key	,
secondary1_changed_on	,
short_description	,
source_url	,
secondary2_changed_on	,
domain_key	,
dw_inserted_on	,
etl_run_number	,
opened_on	,
call_number	,
soft_deleted_flag	,
changed_on	,
changed_by	,
description	,
source_id	,
created_by	,
dw_updated_on	,
created_on	,
cdctype	

