SELECT CASE WHEN count(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END as Result,
CASE WHEN count(1) >0 THEN 'MDS to DWH data validation failed for d_calendar_date.year_end_date' ELSE 'SUCCESS' END as Message
FROM  <<tenant>>_workdb.DS_DATE_SEED SRC
LEFT OUTER JOIN (SELECT MAX(DATE(`DATE`)) AS YEAR_END_DATE,MIN(DATE(`DATE`)) AS YEAR_START_DATE
FROM <<tenant>>_workdb.DS_DATE_SEED
group by CAST(DATE_FORMAT(`DATE`,'%Y') AS SIGNED)
) SRC2   
ON CAST(DATE_FORMAT(SRC.`DATE`,'%Y') AS SIGNED) = CAST(DATE_FORMAT(SRC2.YEAR_START_DATE,'%Y') AS SIGNED) 
LEFT JOIN <<tenant>>_mdwdb.d_calendar_date TRGT 
ON(CONCAT(CONCAT(DATE_FORMAT(SRC.`DATE`,'%Y'),DATE_FORMAT(SRC.`DATE`,'%m')),DATE_FORMAT(SRC.`DATE`,'%d')) =TRGT.row_id)
WHERE SRC2.YEAR_START_DATE<>TRGT.year_end_date
