
SELECT CASE WHEN COUNT(DISTINCT #COLUMN_NAME) <> COUNT(#COLUMN_NAME) THEN 'FAILURE' ELSE 'SUCCESS' END AS Result,
CASE WHEN  COUNT(DISTINCT #COLUMN_NAME) <> COUNT(#COLUMN_NAME) THEN '#COLUMN_NAME has duplicate values' ELSE '#COLUMN_NAME has all distinct values' END AS Message 
FROM #TABLE_NAME 
HAVING COUNT(DISTINCT #COLUMN_NAME) <> COUNT(#COLUMN_NAME) 

