
SELECT CASE WHEN COUNT(#COL_NAME) <> 0 THEN 'FAILURE' ELSE 'SUCCESS' END AS Result,
CASE WHEN  COUNT(#COL_NAME) <> 0 THEN '#COL_NAME has NULL values' ELSE '#COL_NAME has all NOT NULL values' END AS Message 
FROM <<tablename>> 
WHERE #COL_NAME IS NULL

