SELECT
warranty_expiration_date,source_id,soft_deleted_flag,secondary2_changed_on,secondary1_changed_on,row_key,row_id,row_dn_key,row_current_key,retirement_date,purchase_date,pre_allocated,po_number,owned_by,managed_by,install_date,etl_run_number,dw_updated_on,dw_inserted_on,disposal_reason,display_name,created_on,created_date,created_by,comments,changed_on,changed_by,cdctype,assigned_date,asset_tag,asset_substatus_code,asset_status_code,asset_source_url,acquisition_method
FROM usf_mdwdb.d_asset
ORDER BY
warranty_expiration_date
,source_id
,soft_deleted_flag
,secondary2_changed_on
,secondary1_changed_on
,row_key
,row_id
,row_dn_key
,row_current_key
,retirement_date
,purchase_date
,pre_allocated
,po_number
,owned_by
,managed_by
,install_date
,etl_run_number
,dw_updated_on
,dw_inserted_on
,disposal_reason
,display_name
,created_on
,created_date
,created_by
,comments
,changed_on
,changed_by
,cdctype
,assigned_date
,asset_tag
,asset_substatus_code
,asset_status_code
,asset_source_url
,acquisition_method

