
SELECT
acquisition_method
,asset_source_url
,asset_status_code
,asset_substatus_code
,asset_tag
,assigned_date
,cdctype
,changed_by
,changed_on
,comments
,created_by
,created_date
,created_on
,display_name
,disposal_reason
,dw_inserted_on
,dw_updated_on
,etl_run_number
,install_date
,managed_by
,owned_by
,po_number
,pre_allocated
,purchase_date
,retirement_date
,row_current_key
,row_dn_key
,row_id
,row_key
,secondary1_changed_on
,secondary2_changed_on
,soft_deleted_flag
,source_id
,warranty_expiration_date
FROM usf_mdwdb.d_asset 
ORDER BY 
acquisition_method
,asset_source_url
,asset_status_code
,asset_substatus_code
,asset_tag
,assigned_date
,cdctype
,changed_by
,changed_on
,comments
,created_by
,created_date
,created_on
,display_name
,disposal_reason
,dw_inserted_on
,dw_updated_on
,etl_run_number
,install_date
,managed_by
,owned_by
,po_number
,pre_allocated
,purchase_date
,retirement_date
,row_current_key
,row_dn_key
,row_id
,row_key
,secondary1_changed_on
,secondary2_changed_on
,soft_deleted_flag
,source_id
,warranty_expiration_date
