SELECT CASE WHEN COUNT(1) > 0 THEN 'FAILURE' ELSE 'SUCCESS' END AS Result,
CASE WHEN COUNT(1) >0 THEN 
'MDS to DWH data validation failed for d_calander_date.#DWH_column_NAME' ELSE 'SUCCESS' END AS Message
FROM (SELECT  CONCAT(YEAR(DS_DATE_SEED.DATE)
,CASE WHEN MONTH(DS_DATE_SEED.DATE) < 10 THEN CONCAT('0' 
,MONTH(DS_DATE_SEED.DATE)) ELSE MONTH(DS_DATE_SEED.DATE)  END 
,CASE WHEN DAY(DS_DATE_SEED.DATE) < 10 THEN CONCAT('0' 
, DAY(DS_DATE_SEED.DATE))
ELSE DAY(DS_DATE_SEED.DATE) END ) AS row_id,
#STG_column_NAME AS DATE
FROM <<tenant>>_mdsdb.DS_DATE_SEED  
 #STG_Condition
)A
LEFT JOIN <<tenant>>_mdwdb.d_calendar_date
ON d_calendar_date.row_id = A.row_id 
AND CALENDAR_CODE ='0'
WHERE d_calendar_date.#DWH_column_NAME <>
A.DATE
