SELECT
source_id,soft_deleted_flag,short_desc,secondary2_changed_on,secondary1_changed_on,row_key,row_id,row_dn_key,row_current_key,is_inherited,expense_type,expense_summary_type,expense_status,expense_item_category,etl_run_number,dw_updated_on,dw_inserted_on,created_on,created_by,changed_on,changed_by,cdctype
FROM usf_mdwdb.d_expense_item
ORDER by
source_id
,soft_deleted_flag
,short_desc
,secondary2_changed_on
,secondary1_changed_on
,row_key
,row_id
,row_dn_key
,row_current_key
,is_inherited
,expense_type
,expense_summary_type
,expense_status
,expense_item_category
,etl_run_number
,dw_updated_on
,dw_inserted_on
,created_on
,created_by
,changed_on
,changed_by
,cdctype