
SELECT CASE WHEN COUNT(*) >0 THEN 'FAILURE' ELSE 'SUCCESS' END as Result,
CASE WHEN COUNT(*) >0 THEN '#STG_TABLE_NAME has invalid #STG_COL_NAME ' ELSE 'SUCCESS' END as Message 
FROM #MDS_TABLE_SCHEMA.#MDS_TABLE_NAME 
WHERE crc32(CONCAT_WS(' ',sys_id ,sourceinstance, 
CASE WHEN #MDS_COL_NAME IS NULL THEN 'UNSPECIFIED' ELSE date_format(#MDS_COL_NAME,'#FORMAT') END ))  
NOT IN (SELECT crc32(CONCAT_WS(' ',row_id ,source_id,#STG_COL_NAME ) )
FROM #STG_TABLE_SCHEMA.#STG_TABLE_NAME ); 
