SELECT
warranty_expiry_on_key,supplier_key,storage_location_key,status_start_on_key,status_start_on,status_end_on_key,status_end_on,source_id,soft_deleted_flag,secondary2_changed_on,secondary1_changed_on,row_key,row_id,project_key,product_model_key,model_category_key,location_key,etl_run_number,employee_key,dw_updated_on,dw_inserted_on,duration,domain_key,department_key,current_flag,created_on,created_by,cost_center_key,contract_key,changed_on,changed_by,cdctype,asset_substatus_key,asset_status_key,asset_retirement_on_key,asset_key,asset_created_on_key,asset_class_key,asset_assigned_to_key,asset_assigned_on_key
FROM usf_mdwdb.f_asset_status_history
ORDER BY
warranty_expiry_on_key
,supplier_key
,storage_location_key
,status_start_on_key
,status_start_on
,status_end_on_key
,status_end_on
,source_id
,soft_deleted_flag
,secondary2_changed_on
,secondary1_changed_on
,row_key
,row_id
,project_key
,product_model_key
,model_category_key
,location_key
,etl_run_number
,employee_key
,dw_updated_on
,dw_inserted_on
,duration
,domain_key
,department_key
,current_flag
,created_on
,created_by
,cost_center_key
,contract_key
,changed_on
,changed_by
,cdctype
,asset_substatus_key
,asset_status_key
,asset_retirement_on_key
,asset_key
,asset_created_on_key
,asset_class_key
,asset_assigned_to_key
,asset_assigned_on_key