SELECT 
row_id,expense_item_key,parent_expense_item_key,soft_deleted_flag,changed_by,expense_doc_amount,row_key,department_key,expense_type_key,asset_key,base_expense_item_key,changed_on,dw_updated_on,configuration_item_key,created_by,etl_run_number,processed_on_key,secondary1_changed_on,dw_inserted_on,domain_key,expense_created_on_key,expense_loc_amount,expense_item_category_key,expense_user_key,contract_key,source_id,cdctype,doc_currency_key,loc_currency_code,loc_currency_key,expense_summary_type_key,generated_on_key,expense_status_key,expense_created_on,cost_center_key,created_on,doc_currency_code,secondary2_changed_on,location_key
FROM usf_mdwdb.f_expense_item 
ORDER BY 
row_id
,expense_item_key
,parent_expense_item_key
,soft_deleted_flag
,changed_by
,expense_doc_amount
,row_key
,department_key
,expense_type_key
,asset_key
,base_expense_item_key
,changed_on
,dw_updated_on
,configuration_item_key
,created_by
,etl_run_number
,processed_on_key
,secondary1_changed_on
,dw_inserted_on
,domain_key
,expense_created_on_key
,expense_loc_amount
,expense_item_category_key
,expense_user_key
,contract_key
,source_id
,cdctype
,doc_currency_key
,loc_currency_code
,loc_currency_key
,expense_summary_type_key
,generated_on_key
,expense_status_key
,expense_created_on
,cost_center_key
,created_on
,doc_currency_code
,secondary2_changed_on
,location_key