

SELECT CASE WHEN COUNT(1) >0 THEN 'FAILURE' ELSE 'SUCCESS' END as Result,
CASE WHEN COUNT(1) >0 THEN '#STG_TABLE_NAME has invalid #STG_COL_NAME ' ELSE 'SUCCESS' END as Message
FROM usf_mdsdb.#BASE_TABLE BASE
JOIN usf_mdsdb.#BASE2_TABLE BASE2
ON(#JOIN_CONDITION)
WHERE crc32(CONCAT_WS(' ',#BASE_ROW_ID,BASE.sourceinstance,COALESCE(#COALESCE)))
NOT IN (SELECT crc32(CONCAT_WS(' ',row_id ,source_id ,#STG_COL_NAME ))
FROM usf_workdb.#STG_TABLE_NAME );
