CALL app_test.drop_index_if_exists('#TIGER_DWH_SCHEMA','#TIGER_TABLE_NAME','idx_#TIGER_TABLE_NAME_#COLUMN_NAME');

CREATE INDEX idx_#TIGER_TABLE_NAME_#COLUMN_NAME
ON #TIGER_DWH_SCHEMA.#TIGER_TABLE_NAME(row_id,#COLUMN_NAME);

ANALYZE TABLE #TIGER_DWH_SCHEMA.#TIGER_TABLE_NAME;

CALL app_test.drop_index_if_exists('#JAGUAR_DWH_SCHEMA','#JAGUAR_TABLE_NAME','idx_#JAGUAR_TABLE_NAME_#COLUMN_NAME');

CREATE INDEX idx_#JAGUAR_TABLE_NAME_#COLUMN_NAME
ON #JAGUAR_DWH_SCHEMA.#JAGUAR_TABLE_NAME(row_id,#COLUMN_NAME);

ANALYZE TABLE #JAGUAR_DWH_SCHEMA.#JAGUAR_TABLE_NAME;
